### ISSUE TITLE
Problema con configuración de clion en macOS

### ISSUE THREAD

**Issue by marr64** [PI-ITBA/2024_01#1]
No me reconoce la imagen en los settings del toolbar 😭 instale desde terminal el archivo .txt pero no se que pasa...
<img width="1440" alt="Screen Shot 2024-03-03 at 01 24 17" src="https://github.com/PI-ITBA/2024_01/assets/127711549/33740792-ad06-4e6c-a815-964e1b00d34d">

muchas gracias!

**Comment by fmeola** [comment]
Hola. Primero asegurate que la imagen de Ubuntu se descargó correctamente corriendo desde la terminal el comando `docker images`. Deberías ver algo así:

```
clion/ubuntu/cpp-env           1.0              dae0d16f13fd   6 weeks ago     1.2GB
```

Si eso está bien entonces puede ser un problema del CLion. Probaría la opción [Invalidate Caches](https://www.jetbrains.com/help/clion/invalidate-caches.html) que está en el menú File. Tildá todas las opciones y se reiniciará CLion. Una vez reiniciado volvé a agregar el Toolchain y la imagen debería aparecer.

Si seguís con problemas te recomiendo por ahora usar [CLion con Pampero](https://pi-itba.github.io/tutoriales/clion-pampero.html) y la próxima clase presencial que tengas te acercás con la compu así alguien te puede dar una mano con eso.
