### ISSUE TITLE
REC 1C_2023 EJ 3

### ISSUE THREAD

**Issue by juliapriolo** [PI-ITBA/2024_01#100]
Hola! resolvi este ejercicio de dos formas distintas. 
Escribir la función queContiene que reciba dos strings s1 y s2. El string s1
puede contener cualquier valor ASCII. El string s2 contiene únicamente letras
minúsculas o mayúsculas (no debe validarse, se asegura que sólo son letras del
alfabeto inglés). La función debe retornar cuántos caracteres de s1 son letras
contenidas en s2, sin distinguir entre minúsculas o mayúsculas. 

```c
//programa de pruba
#include <stdio.h>
#include <ctype.h>
#include <assert.h>
#define LETRAS 'Z' - 'A' + 1

int queContiene(char s1[], char s2[]);

int main(void) {
    int c = queContiene("Ahora me pongo a llorar", "zaMo");
    assert(c==9); // A o a m o o a o a
    c = queContiene("Ahora me pongo a llorar", "");
    assert(c==0);
    c = queContiene("143 I love you", "xaprarczd");
    assert(c==0);
    c = queContiene("Mamaaa, just killed a man, put a gun...",
    "xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxxyxyxxyxxyM");
    assert(c==3); // 3 veces la letra m, una vez mayúscula y
// dos veces minúscula
return 0;
}
```

La primera fue:
```c
int queContiene(char s1[], char s2[]){
    int contador = 0;
    int esta;

    for(int i=0; s1[i] != '\0'; i++){
        if(isalpha(s1[i])){
        esta = 0;
        for(int j=0; s2[j] != '\0' && !esta; j++){
            if(tolower(s1[i]) == tolower(s2[j])){
                contador++;
                esta = 1;
                }
            }            
        }
    }
return contador;
}
```
Despues se me ocurrio que capaz podria haber usado un marcador para no tener que recorrer el segundo string por cada letra del string 1, osea que solo lo recorra una vez pero uso un vector auxiliar
```c
int queContiene(char s1[], char s2[]){
    int contador = 0;
    int letras[LETRAS] = {0};
    char letra;
    int j=0;
    
    while(s2[j] != '\0'){
        letra = toupper(s2[j]);
        letras[letra - 'A']++;
        j++;
    }

    for(int i=0; s1[i] != '\0'; i++){
        if(isalpha(s1[i])){
            letra = toupper(s1[i]);
            if(letras[letra - 'A'] > 0){
                contador++;
            }
        }
    }
return contador;
}
```

Estan bien? Que opcion seria la mas eficiente?

**Comment by marcelogarberoglio** [comment]
Es preferible la versión 2, que hace menos recorridos. Salvo casos particulares, donde se aclare que el vector es corto (por ejemplo contiene sólo una palabra, o un número telefónico), conviene evitar hacer varios recorridos. Y en estos casos donde los valores están acotados podemos usar un vector auxiliar como el de letras.
Sólo le haría un par de cambios menores:
-el vector letras puede ser de char en vez de int, para que ocupe menos
-en vez de incrementar por cada aparición se le puede asignar 1 (por si una misma letra aparece 256 veces
-Si s1 o s2 están vacíos se puede retornar cero directamente sin recorrer ningún vector
