### ISSUE TITLE
Parcial 1, 2018 2C Ej 1

### ISSUE THREAD

**Issue by sratto0** [PI-ITBA/2024_01#107]
Buen dia, queria saber si mi codigo es eficiente y tiene buen estilo(le hice un test con los ejemplos y lo pasa).
La consigna es:

     Escribir una función que, dada una matriz de enteros de N filas y M columnas, arme los números que se
forman con cada fila y retorne cuál es el máximo. Para poder armar un número con los elementos de una fila,
todos sus elementos deben contener un número entero entre 0 y 9 inclusive.
Si hubiera números negativos o de más de una cifra, no se completa el armado del número.
Si no se pudo armar ningún número, retorna -1.

```c
#define N 4
#define M 4

int valido(int m[][M], int fila){
    for(int j=0;j<M;j++){
        if(m[fila][j]<0 || m[fila][j]>9){
            return 0;
        }
    }
    return 1;
}

int armado(int m[][M], int fila){
    int num=0;
    for(int j=0;j<M;j++){
        num=((num*10)+m[fila][j]);
    }
    return num;
}

int max(int m[][M]){
    int max=-1, num;
    for(int i=0;i<N;i++){
        if(valido(m, i)){
            num=armado(m, i);
            max=(num>max? num:max);
        }
    }
    return max;
}

int main(){
    int m[N][M]={
        {16,3,2,13},
        {5,10,11,8},
        {9,6,7,12},
        {4,15,14,1},
    };
    int num=max(m);
    assert(num==-1);

    int m2[N][M]={
        {1,3,2,5},
        {5,0,1,8},
        {9,6,7,2},
        {4,5,4,1},
    };
    int num2=max(m2);
    assert(num2==9672);

    int m3[N][M]={
        {1,3,2,5},
        {5,4,11,8},
        {9,6,-7,2},
        {4,5,4,1},
    };
    int num3=max(m3);
    assert(num3==4541);

    puts("Ok");
    return 0;
}``

**Comment by marcelogarberoglio** [comment]
Se podría evitar recorrer dos veces cada fila, haciendo que armado verifique el valor de cada elemento antes de agregarlo a num, y si es inválido retorne -1.

**Comment by sratto0** [comment]
buenisimo, muchas gracias!
