### ISSUE TITLE
Ejercicio parcial  - Macro NO_ACENTO

### ISSUE THREAD

**Issue by aguegea** [PI-ITBA/2024_01#110]
![Screenshot 2024-04-18 at 11 32 34 AM](https://github.com/PI-ITBA/2024_01/assets/119601794/b8fb9de8-dd42-42f5-b170-8b4331cbbc83)
Buen día, tengo dudas sobre mi resolución de este ejercicio. Al no estar las vocales acentuadas continuas en ASCII, lo hice por casos.

```c
#define NO_ACENTO(c) ( ( (c) == 'á' ? (c) -= ('á' - 'a') : ( (c) == 'é' ? (c) -= ('é - e') : ( (c) == 'í' ? (c) -= ('í - i') : ( (c) == "ó" ? (c) -= ('ó - o') : ( (c) == 'ú' ? (c) -= ('ú' - u) : (c) ) ) ) ) ) )
```

**Comment by marcelogarberoglio** [comment]
Sí, hay que hacerlo con condicionales anidados, pero podría ser más simple, asignando directamente, o sea

#define NO_ACENTO(c) ( ( (c) == 'á' ? (c = 'a') : ( ...
