### ISSUE TITLE
Parcial 1 2018 1C EJ 3

### ISSUE THREAD

**Issue by sratto0** [PI-ITBA/2024_01#112]
Buen dia, queria saber como puedo hacer para que sumaFila y sumaCol me queden en una misma funcion para mejorar el codigo.
Este es el enunciado:
   Se dice que una matriz de números enteros es "escalable" si para cada fila (excepto la primera) la suma de sus
elementos es igual a 1 + la suma de los elementos de la fila anterior, y para cada columna (excepto la primera)
se cumple que la suma de sus elementos es igual a la suma de la columna anterior + 1.
Escribir una función que reciba una matriz de enteros y retorne 1 si es escalable y 0 sinó. Agregar los
parámetros que sean necesarios.

```c
int sumaFila(int m[][M], int fila){
    int sumaf=0;
    for(int i=0;i<M;i++){
        sumaf+=(m[fila][i]);
    }
    return sumaf;
}

int sumaCol(int m[][M], int col){
    int sumac=0;
    for(int i=0;i<M;i++){
        sumac+=(m[i][col]);
    }
    return sumac;
}

int escalable(int m[][M]){
    int fil=sumaFila(m, 0);
    int col=sumaCol(m, 0);
    for(int i=1;i<M;i++){
        int s2f=sumaFila(m, i);
        int s2c=sumaCol(m, i);
        if(fil+i!=s2f){
            return 0;
        }else if(col+i!=s2c){
            return 0;
        }
    }
    return 1;
}

int main(){
    int m[M][M]={
        {1,1,1,1},
        {1,2,1,1},
        {1,1,2,2},
        {1,1,2,3},
    };
    int rta=escalable(m);
    assert(rta==1);

    int m2[M][M]={
        {1,1,1,-1},
        {1,2,1,1},
        {1,1,2,2},
        {1,1,2,3},
    };
    int rta2=escalable(m2);
    assert(rta2==0);

    puts("Ok");
    return 0;
}

**Comment by marcelogarberoglio** [comment]
No está mal que esté así, lo que cambiaría es sumar la columna sólo si la fila está bien, sólo cambiar el orden de las llamadas, o sea

      int s2f=sumaFila(m, i);
        if(fil+i!=s2f){
            return 0;
        int s2c=sumaCol(m, i);

Se podría hacer con una sola función si la matriz es cuadrada, haciendo la suma de m[fila][i] para la fila y de m[i][fila] para la columna y retonar esos dos valores, Si las matrices no necesariamente son cuadradas entonces debe haber dos funciones.
En caso de que dejes las dos funciones, la que suma la fila debería recibir sólo el vector, no la matriz y qué fila sumar

**Comment by sratto0** [comment]
perfecto, muchas gracias!!
