### ISSUE TITLE
2C2019 EJ 4

### ISSUE THREAD

**Issue by juliapriolo** [PI-ITBA/2024_01#114]
Hola! Resolvi este ejercicio de la soguiente forma pero no funciona cuando la matriz es antisimetrica, no entiendo porque. 

La consigna era: Hacer una funcion simAsim que recibe una matriz cuadrada de enteros de dimension DIM (cte predefinida)
y retorna 1 si es simetrica -1 si no es simetrica pero es antisimetrica o 0 en otro caso.

Por otro lado, si la matriz es simetrica o antisimetrica mi codigo recorre toda la matriz pero no se me ocurre hacerlo de otra forma para que evite recorrer toda la matriz

```c
#include <stdio.h>
#define DIM 4

int simAsim(int matriz[][DIM]);

//PROGRAMA DE PRUEBA
int main(void){
    int m1[][DIM] = {{1,1,1,1,},{1,1,1,1},{1,1,2,2},{1,1,2,3}}; //es simetrica
    int m2[][DIM] = {{0,-1,1,2},{1,0,1,-3},{-1,-2,0,-21},{-2,3,21,0}};//es anti

    printf("matriz 1: %d, matriz 2:  %d\n", simAsim(m1), simAsim(m2));

return 0;
}


int simAsim(int matriz[][DIM]){
    int sim = 1;
    for(int i=0; i<DIM;i++){
        for(int j=0; j<DIM; j++){
            if(matriz[i][j] != matriz[j][i]){
                sim = 0;
                if((matriz[i][j] != -matriz[j][i])){
                    return 0;
                }
            }
        
        }
    }
return (sim ? 1 : -1);
}

```

**Comment by ImNotGone** [comment]
```c

**Comment by ImNotGone** [comment]
c0| c1|c2|c3
--|---|----|--
0  | -1 | 1|  2
1  |  0  |1| -3
-1 |-2 | 0 |-21
-2 |  3 | 21| 0
