### ISSUE TITLE
Recu Parcial 1 2018 1C EJ 1

### ISSUE THREAD

**Issue by sratto0** [PI-ITBA/2024_01#115]
Buenas, queria saber si mi codigo es eficiente y tiene buen estilo.(una parte del main esta comentada porque son las matrices con N=4, las que no estan comentadas tienen N=3)
El enunciado es:
   Escribir una función que, dada una matriz de N filas y N columnas determine si es un “cuadrado
mágico”.
Una matriz es cuadrado mágico cuando:
● es cuadrada (NxN) (donde N es una constante simbólica)
● tiene todos los números del 1 al N2
● la suma de los elementos de cualquier fila es igual a la suma de los elementos de cualquier
columna

```c
int numeros(int m[][N]){
    int vec[N*N]={0};
    for(int i=0;i<N;i++){
        for(int j=0;j<N;j++){
            if(vec[m[i][j]-1]!=0){
                return 0;
            }else
                vec[m[i][j]-1]++;
        }
    }
    return 1;
}

int suma(int m[][N], int fila){
    int num=0, num2=0;
    for(int i=0;i<N;i++){
        num+=m[fila][i];
        num2+=m[i][fila];
    }
    if(num!=num2){
        num=0;
    }
    return num;
}

int magica(int m[][N]){
    int num=suma(m, 0), num2;
    if(num==0){
        return 0;
    }
    if(numeros(m)){
        for(int i=1;i<N;i++){
            num2=suma(m, i);
            if(num!=num2){
                return 0;
            }
        }
    }else return 0;
    return 1;
}

int main(){
    /*int m[N][N]={
        {16,3,2,13},
        {5,10,11,8},
        {9,6,7,12},
        {4,15,14,1},
    };
    int rta=magica(m);
    assert(rta==1);

    int m2[N][N]={
        {16,4,5,10},
        {11,2,3,6},
        {12,9,13,15},
        {7,8,1,14},
    };
    int rta2=magica(m2);
    assert(rta2==0);*/

    int m3[N][N]={
        {4,9,2},
        {3,5,7},
        {8,1,6},
    };
    int rta3=magica(m3);
    assert(rta3==1);

    int m4[N][N]={
        {4,9,2},
        {4,5,6},
        {7,1,7},
    };
    int rta4=magica(m4);
    assert(rta4==0);

    puts("Ok");
}

**Comment by marcelogarberoglio** [comment]
Estás recorriendo la matriz dos veces, podrías hacer la verificación de números repetidos a medida que vas sumando
Faltaría validar que cada número esté entre 1 y N*N antes de hacer
    if(vec[m[i][j]-1]!=0){
ya que estarías accediendo fuera del vector

**Comment by sratto0** [comment]
Ahi hago la verificacion y la suma en una sola funcion y valido que este entre 1 y N*N, estaria mejor asi?

```c
int suma(int m[][N], int fila){
    int vec[N*N]={0};
    int num=0, num2=0;
    for(int i=0;i<N;i++){
        for(int j=0;j<N;j++){
            if(vec[m[i][j]-1]==0 && m[i][j]>=1 && m[i][j]<=N*N){
                vec[m[i][j]-1]++;
                num+=m[fila][i];
                num2+=m[i][fila];
            }else num=0;
        }
    }
    if(num!=num2){
        num=0;
    }
    return num;
}

int magica(int m[][N]){
    int num=suma(m, 0), num2;
    if(num==0){
        return 0;
    }
    for(int i=1;i<N;i++){
        num2=suma(m, i);
        if(num!=num2){
            return 0;
        }
    }
    return 1;
}

**Comment by marcelogarberoglio** [comment]
Habría que invertir las condiciones en este if
    if(vec[m[i][j]-1]==0 && m[i][j]>=1 && m[i][j]<=N*N){
Ya que si el número es negativo o más grande que N*N accedés a memoria inválida
y en vez de setear num en cero deberías hacer return 0, para no seguir sumando si era inválido o repetido.

**Comment by sratto0** [comment]
buenisimo, muchas gracias!!!
