### ISSUE TITLE
Parcial 1 2Q2023 - EJ3

### ISSUE THREAD

**Issue by felipeboya** [PI-ITBA/2024_01#123]
Hola, tengo una consulta mas que nada sobre estilo de un ejercicio de parcial del cuatrimestre pasado:

El enunciado es: Se dice que una palabra o frase es anagrama de otra palabra o frase si ambas
están compuestas por las mismas letras y con la misma cantidad de apariciones de
cada letra, sin tener en cuenta los blancos.
Por ejemplo "anagrama" es anagrama de "amar gana", pero no de "margana", ya que
esta última tiene sólo 3 letras 'a' en vez de 4.
Escribir la función anagrama que reciba dos strings formados únicamente por letras
del alfabeto inglés y espacios (no es necesario validarlo, se asume que ambos cumplen con
esta condición) y retorne 1 si ambos son anagramas o 0 si no lo son.

Mi solucion fue la siguiente: 

```
#define CANT_LETRAS ('z' - 'a' + 1)

int anagrama ( const char * s1, const char * s2 );
int verificaApariciones ( const int v[], unsigned int dim );

int main(void){
    char * s = "anagrama";
    assert(anagrama(s, "amar gana"));
    assert(anagrama("enrique", "quieren"));
    assert(anagrama(s, s));
    assert(anagrama(" ", ""));
    assert(anagrama("amar gana", s));
    assert(anagrama("", ""));
    assert(anagrama("a gentleman", "elegant man"));
    assert(anagrama("a", "") == 0);
    assert(anagrama("mar", "amar") == 0);

    puts("OK!");

    return 0;
}

int anagrama ( const char * s1, const char * s2 ){
    int aux[CANT_LETRAS] = {0};

    int letra;

    while ( *s1 != 0 ){
        letra = tolower(*s1);
        if ( letra != ' ' ){
            aux[letra - 'a']++;
        }
        s1++;
    }

    while ( *s2 != 0 ){
        letra = tolower(*s2);
        if ( letra != ' ' ){
            aux[letra - 'a']--;
        }
        s2++;
    }

    return verificaApariciones(aux, CANT_LETRAS);
}

int verificaApariciones ( const int v[], unsigned int dim ){
    for ( int i = 0; i < dim; i++ ){
        if ( v[i] != 0 )
            return 0;
    }

    return 1;
}
```

En la funcion anagrama, los dos ciclos while son muy similares, pero con la diferencia que uno suma al vector de apariciones y el otro resta. Mi pregunta es si eso seria mejor dejarlo asi, o hacer dos funciones distintas que hagan eso, o hacer una sola funcion que reciba un parametro que le indique si debe restar o sumar. 

Saludos y gracias.

**Comment by marcelogarberoglio** [comment]
Los dos ciclos los podemos dejar así, pero no debería ser necesaria la función verificaApariciones.
En el segundo ciclo, si antes de restar, en aux[letra-'a'] tenés cero, quiere decir que no son anagramas
Si a los dos ciclos le agregás que cuenten la cantidad de letras, al final esa cuenta te tiene que dar igual

**Comment by felipeboya** [comment]
Perfecto gracias!!
