### ISSUE TITLE
Ejercicio Teórica Miércoles 24/04

### ISSUE THREAD

**Issue by Frandtuzilla** [PI-ITBA/2024_01#129]
Que tal! Quería saber si este ejercicio que vimos recién con Marcelo en la teórica estaba bien:

```
#include <stdio.h>
#include <stdlib.h>

int
getLine(char s[], size_t max){
    int c;
    int i = = 0;
    while ((c=getchar() != EOF && c != '\n') ) {
        if( i<max){
            s[i++] = c;
        }
    }
    s[i] = 0;
    return i; 
}

char **
vecStrings( int * cantStrings){

    char ** pStrings;

    pStrings = (char **)malloc((*cantStrings) * sizeof(char *));
    
    if(pStrings == NULL){
        printf("Error, no hay suficiente memoria.\n");
        return NULL;
    }

    for (int i = 0; i < (*cantStrings); i++) {
        
        int dim;

        do{
            dim = getint("Ingrese tamaño del string:");
        }while( dim <= 0);

        char * aux = (char *)malloc((dim+1) * sizeof(char));

        if(aux == NULL){
            printf("Error, no hay suficiente memoria.\n");
            return NULL;
        }
        
        printf("Ingrese la cadena de caracteres %d: ", i + 1);
        getLine(aux, dim+1);
        pStrings[i] = aux;
    }

    return pStrings;
}
```

**Comment by marcelogarberoglio** [comment]
Está bastante bien, algunos comentarios:
1) recuerden que no es necesario en la práctica y en el parcial validar los allocs, pero en caso de hacerlo (por ejemplo para el TPE) hay que dejar la memoria en forma consistente, en este ejemplo, si alguno de los mallocs para los strings falla, antes de hacer return tendrías que liberar los strings anteriores y el vector, pero inisisto, eso para el TPE. También que en algunos casos (por ejemplo en pampero) malloc y callod nunca retornan NULL, por lo que la forma segura de controlar el error es con errno
2) a getline tendrías que pasarle dim, no dim+1
3) no es necesario castear la rta de malloc
4) no entiendo por qué cantStrings es un puntero. Eso sería si la cantidad de strings la decide la función, o si le informara que pudo leer menos de los solicitados, pero ya recibe cuántos strings leer y lee sí o sí esa cantidad.

La aproximación que vamos a ver el lunes para leer los strings va a ser más sencilla, vamos a asumir un máximo para cada string, y si el usuario ingresa algo mayor se lo trunca. Pero el manejo de memoria y lectura será como el que planteaste acá.
