### ISSUE TITLE
tp6_ej26

### ISSUE THREAD

**Issue by NolascoJ** [PI-ITBA/2024_01#134]
Buenas, tenia una duda, no entiendo porque el ultimo assert del programa no lo pasa, puse un printf para ver que estaba pasando y es como que una parte del string anterior queda guardada en el nuevo string, entonces copia lo que tiene que copiar, y una parte del otro string. Queria saber porque pasa esto, como se puede solucionar y si es porque hay un problema en la logica de la funcion. Gracias!

PD: Perdon por el formato,del texto, no se porque solo una parte se pasa a el formato de codigo. 

#include <stdio.h>
#include <string.h>
#include <assert.h>

void insertaDesde(char * s1 , char * s2, char letra);

int main(void) {
    char str1[60] = "manuel";
    char str2[] = "javi";
    insertaDesde(str1, str2,'n');
    assert(strcmp(str1,"majavi")==0);

    char str3[20];
    strcpy(str3, "manuel");
    insertaDesde(str3, "javi" ,'l');
     printf("%s\n", str3);
    assert(strcmp(str3,"manuejavi")==0); // muestra manuejavi

    char str4[60];
    strcpy(str4, "lalala");
    insertaDesde(str4, "javi",'j');
     printf("%s\n", str4);
    assert(strcmp("lalala",str4)==0);

    insertaDesde(str4, "javier ibaniez de toledo",'l');
     printf("%s\n", str4);
    assert(strcmp("javier ibaniez de toledo",str4)==0);

    strcpy(str4,"12345");
    insertaDesde(str4, "6789abcdefgh",'5');
    printf("%s\n", str4);
    assert(strcmp("12346789abcdefgh",str4)==0);

    puts("OK!");
    return 0;
}

void insertaDesde(char * s1 , char * s2, char letra){
    int flag=1;
    for(int i=0; flag && s1[i] ; i++ )
    if(s1[i] == letra){
        for(int j=0 ; s2[j] ; j++){
            s1[i++]=s2[j];
        }
        flag=0;
    }
}

**Comment by marcelogarberoglio** [comment]
Falta copiar el cero final

**Comment by NolascoJ** [comment]
> Falta copiar el cero final

Perfecto, gracias.
