### ISSUE TITLE
TP4ej3

### ISSUE THREAD

**Issue by InformationSource** [PI-ITBA/2024_01#14]
Buenas, tengo una duda de como hacer para que los datos en una tabla me queden tabulados correctamente. Muestro mi solucion pero esta mal porque no tiene sentido que se tenga que hacer a ojo

#include <stdio.h>
#define PI 3.14
#define VOL(cm) (4.0/3)*PI*(cm)*(cm)

int main(void){
    printf("Radio de esfera\tVolumen\n");
    for(int radio = 1; radio <= 10; radio++)
        printf("%d\t\t\t\t%g\n", radio, VOL(radio));
}

**Comment by marcelogarberoglio** [comment]
Para que salgan tabulados imprimirlos con punto fijo: por ejemplo %.2f en vez de %g

printf("%3d\t%.2f\n", radio, VOL(radio));

Lo que está mal es la macro, ya que te va a quedar por ejemplo

(4.0/3)3.14(1)*(1)

faltaría un * antes y después de PI
