### ISSUE TITLE
Autoevaluación 4

### ISSUE THREAD

**Issue by AugustoOspal** [PI-ITBA/2024_01#142]
No entiendo algunas de las respuestas correctas de la autoevaluación 4:

Pregunta 3:	La cantidad de bytes que usa un int no depende de la arquitectura de la computadora? El formato, en este caso little-endian, también no depende de la arquitectura?

Pregunta 4:	v al ser un array, porque lo usan como un L value haciendo v++? No era que no se podía y que teníamos que copiar la dirección en un puntero del mismo tipo como se hace en la pregunta 5?	

Saludos y gracias

**Comment by ImNotGone** [comment]
Mandarias mas detallado? Asi leo todo? Con las resp y la consigna

**Comment by marcelogarberoglio** [comment]
3: La consigna dice "si se compila y ejecuta en Linux". El int sólo ocupará 2 bytes si están usando un Windows muy viejo. Es cierto que algunas arquitecturas (procesadores RISC) son big-endian, pero asumimos que lo ejecutarán en Pampero o en una PC o notebook propia, entonces será little-endian. Asumiendo todo eso, cómo se llega al número está explicado en los comentarios.
4: en clase se hicieron varios ejercicios donde se recibe un array y nos desplazamos usando notación de punteros. Lo que se recibe no es "un array"  sino la dirección del primer elemento y se guarda en una variable. Entonces v, en la función sumAll, es una variable de tipo puntero a int que tiene la dirección del primer elemento del array. Como toda variable, se puede modificar. 
En el ejercicio 5 v sí es una constante, por lo tanto no se puede modificar.

**Comment by AugustoOspal** [comment]
Perfecto, gracias!
