### ISSUE TITLE
TP7_EJ20

### ISSUE THREAD

**Issue by roccoppp** [PI-ITBA/2024_01#151]
Hola! quiero saber cual es el error en este codigo, me da segmentation fault cuando lo compilo.
Lo compilo con Wall y no me tira ningun warning.
En el assert cambie la primera declaracion para no usar el typedef.

`   #include <stdio.h>
#include <math.h>
#include <ctype.h>
#include "/home/rocco/ARCHIVOS/getnum.h"
#include <stdlib.h>
#include <time.h>  
#include <assert.h>
#include <string.h>

#define BLOQUE 6

char ** aprobados(char * alumnos[], int * notas){
    char ** aprobados;
    int  t = 0;

    for (int i = 0; alumnos[i][0] != 0 ; i++)
    {
        if(i % BLOQUE == 0 ){
            aprobados = realloc(aprobados,( (BLOQUE + t) * sizeof(char *)));
            
        }
        if (notas[i] >= 4)
        {
            aprobados[t] = malloc((strlen(alumnos[i]) + 1) * sizeof(char));
            strcpy(aprobados[t++], alumnos[i]);
        }
        
    }
    return aprobados;
}

int main(void){

    char *alumnos[6] = {"Juan", "Pedro", "Martin", NULL};
    int notas[] = {1, 4, 10, 2, 10, 11};
    
    char ** apr = aprobados(alumnos, notas);
    if(apr == NULL){
        printf("No hay suficiente memoria!\n");
        return 1;
    }
    assert(!strcmp(alumnos[1], apr[0]) && !strcmp(alumnos[2], apr[1]) && !strcmp(alumnos[3], apr[2]));

    puts("OK!");
    // En este programa no liberamos la memoria que utilizamos. Que ocurre si compilamos con "-fsanitize=address"?
    return 0;
}    `

**Comment by marcelogarberoglio** [comment]
No puede dar segmentation fault cuando compilás. Si te da segfault es cuando lo ejecutás.
En todo caso, para que te podamos asistir tendrías que:
1) Si es error de compilación -> enviarnos el mensaje que te tira (error, línea, etc.)
2) Si es de ejecución, asegurate de incluir en la compilación el flag de sanitizer y el -g, y copianos el mensaje que te muestra (en texto o imagen, no importa)

**Comment by marcelogarberoglio** [comment]
Aunque a simple vista se que usás aprobados para la función y para el puntero, que no está inicializado en NULL, por lo que seguramente falla el primer realloc

**Comment by roccoppp** [comment]
El error es cuando lo ejecuto. 
Cambie el casteo de aprobados  de la siguiente manera y sigue pasando lo mismo:
char ** aprobados  = NULL
Cuando lo compilo con sanitizer y -g me tira este error:
AddressSanitizer:DEADLYSIGNAL
=================================================================
==672571==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x558a927c6693 bp 0x7fffc554dd90 sp 0x7fffc554dd60 T0)
==672571==The signal is caused by a READ memory access.
==672571==Hint: address points to the zero page.
    #0 0x558a927c6693 in aprobados /home/rocco/ARCHIVOS/TP7/aprobas.c:17
    #1 0x558a927c6a24 in main /home/rocco/ARCHIVOS/TP7/aprobas.c:38
    #2 0x7f31ab1fed8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #3 0x7f31ab1fee3f in __libc_start_main_impl ../csu/libc-start.c:392
    #4 0x558a927c6384 in _start (/home/rocco/ARCHIVOS/TP7/algo+0x2384)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/rocco/ARCHIVOS/TP7/aprobas.c:17 in aprobados
==672571==ABORTING

**Comment by ImNotGone** [comment]
pasa el codigo entero y encerralo entre 3 comillas francesas
\`\`\`c
<codigo>
\`\`\`
asi se ve asi:
```c
int main() {
    return 0;
}
```

**Comment by marcelogarberoglio** [comment]
Te está diciendo que en la línea 17 desreferenciás NULL. El último alumno tiene como puntero NULL y vos preguntás si el primer char es cero

Además está mal este if

 if(i % BLOQUE == 0 ){

debería ser t y debería estar dentro del siguiente if, hacerlo sólo si vas a copiar
