### ISSUE TITLE
Taller 6 - Ej3

### ISSUE THREAD

**Issue by matsdah** [PI-ITBA/2024_01#155]
Buenas noches, como les va? Mi duda no tiene que ver tanto con el ejericio, sino con el criterio que se corregira en el segundo parcial con respecto a la memoria dinamica. Haria falta (con referencia al ejercicio de abajo) crear un puntero a int 'auxiliar' que haga realloc por si es NULL, y luego igualar punteros? Muchas gracias.

```c

#include <stdio.h>
#include <stdlib.h>
#define BLOQUE 10

int * superVector(){
    int c, contador = 0;
    int * arr = NULL;
    while((c = getchar()) != EOF){
        if(contador % BLOQUE == 0){
            arr = realloc(arr, (BLOQUE + contador) * sizeof(arr[0]));
        }
        arr[contador++] = c;
    }
    arr = realloc(arr, contador * sizeof(arr[0]));
    return arr;
}

```

**Comment by marcelogarberoglio** [comment]
Se aclaró en clase que no se pedirá que validen las funciones malloc, realloc, etc en el parcial, pero sí en el TPE final.
