### ISSUE TITLE
Duda sobre rand() y srand()

### ISSUE THREAD

**Issue by JuaniRaggio** [PI-ITBA/2024_01#17]
Estuve haciendo ejercicios con rand y me paso que, usando el srand(time(NULL)), a pesar de que los numeros estaban bien distribuidos en el intervalo y cambiaban en cada ejecicion del programa, el primer numero siempre es muy parecido, nose si es porque mi funcion no esta del todo bien o si asi funciona el rand.
El programa que adjunte, lo corri varias veces y la media me da en 14.022, cuanto mayor ponga el limite del while mas cerca de 14 me daba por lo que entiendo que esta bien distribuido, pero siempre el primer numero es muy parecido. Las ultimas 3 veces que corri el programa, los "primer numero" fueron estos:
19.351 19.3303 19.3283
Si recompilo el programa y lo vuelvo a correr, el primer numero cambia pero en las ejecuciones que haga con ese .o, los "primer numero" siguen siendo muy similares

int main(){
    int a=23, b=5;
    unsigned long i=0;
    srand(time(NULL));
    do {
        printf("%g ", numRandEnRango(a, b));
        ++i;
    }while(i<=10000);
}

//randNormalize devuelve un numero random [0;1] en ese rango
double randNormalize(){
    return rand()/((double)RAND_MAX+1);
}

double numRandEnRango(int izq, int der){
    return (randNormalize()*(der-izq))+izq;
}

**Comment by marcelogarberoglio** [comment]
El programa está bien así. ¿Estás usando una mac sin usar el gcc de pampero? Porque ese comportamiento lo vi en IOS, que usan clang, que el primer valor de rand es siempre el mismo, y recién en el segundo toman la semilla de time(NULL)

**Comment by JuaniRaggio** [comment]
Estoy usando mac pero con el gcc-13, que es el que descargue de homebrew

**Comment by JuaniRaggio** [comment]
ahi lo probe en pampero y funciona con el srand desde el primer numero, pense que el de homebrew era el mismo

**Comment by marcelogarberoglio** [comment]
No, no es el mismo. Te deja usar el "comando" gcc pero es un alias para clang, podés comprobarlo escribiendo en la terminal
gcc --version

**Comment by JuaniRaggio** [comment]
<img width="607" alt="Screenshot 2024-03-27 at 13 36 21" src="https://github.com/PI-ITBA/2024_01/assets/165173497/4c5a04a0-5094-452b-bb1f-f5c729bc3941">

El de arriba es el que tengo yo y el de abajo es el de pampero

**Comment by marcelogarberoglio** [comment]
Entonces sí tenés instalado gcc, pero no sé si lo estás usando. Si lo estabas usando por línea de comandos como gcc-13 estás usando el gcc, pero faltaría ver qué te dice si hacés
gcc --version   
(no gcc-13 --version)
y en caso de estar usando un IDE asegurarte de tener seteado gcc-13 como compilador
Recomiendo seguir este tutorial para que te asegures de usar el compilador correcto, sobre todo para la segunda parte de la materia y el TPE, que será necesario usarlo: https://pi-itba.github.io/tutoriales/gcc-macos.html
No sé si @fmeola  tiene algo para agregar, que es el experto en Mac de la cátedra.

**Comment by JuaniRaggio** [comment]
Cuando compilo pongo gcc-13 para que no use el clang porque si pongo solo gcc, ahi si me usa el clang. De todas formas, yo en toolchains configure para que use por default el gcc-13. Quizas lo configure mal, de ultima el viernes que viene o la proxima clase presencial que haya hablo con franco a ver si me puede dar una mano. Adjunto foto de lo que tengo el toolchains a ver si esta bien
<img width="677" alt="Screenshot 2024-03-27 at 14 49 38" src="https://github.com/PI-ITBA/2024_01/assets/165173497/95f988b2-9007-4dc4-8696-443f39ad3d26">

**Comment by fmeola** [comment]
@JuaniRaggio Estás usando la versión de GCC correcta. En Mac la primera invocación de rand hay que descartarla, incluso si estás usando el GCC Gnu como el que está en Pampero. No encontré hasta el momento una corrección a esta situación.
Lo que podés hacer es editar tu randomize() para que sea una función que además de setear la semilla haga una invocación a rand() y la descarte:

```
void randomize(void) {
    srand((int) time(NULL));
    rand();
}

```
