### ISSUE TITLE
TP09 Ej_10

### ISSUE THREAD

**Issue by JuanIgnacioBridoux** [PI-ITBA/2024_01#173]
Hola, buenos días. Quería consultar si mi solución era correcta. Mi primera idea fue usar una wrapper pero no sé si es lo que pide el ejercicio (al pedir una función recursiva en lugar de resolverlo de forma recursiva).

![image](https://github.com/PI-ITBA/2024_01/assets/142061801/8a87e446-c5c5-4acc-b53d-cc3208ad75a7)

```c
#include <stdio.h>
#include <string.h>
#include <assert.h>

void invertirStringRec(char origen[], char destino[], unsigned int dim) {
    if (dim == 0)
        return;
    else {
        destino[dim-1]=origen[0];
        invertirStringRec(origen+1, destino, dim-1);
    }
}

void invertirString(char origen[], char destino[]) {
    int dim = strlen(origen);
    invertirStringRec(origen, destino, dim);
}
```

**Comment by marcelogarberoglio** [comment]
La forma más simple es con una wrapper, ya que es similar a la solución para palíndromo. Pero esta se puede hacer también sólo con los dos strings.

**Comment by teofum** [comment]
Hay una solución para hacerla sin wrapper (ya que el ejercicio pide "una función recursiva") sin llamar `strlen` en cada iteración? Haciendo eso terminé con esta solución:

```c
void reverse(char *s, char *t) {
  if (s[0] != '\0') {
    t[strlen(s) - 1] = s[0];
    reverse(s + 1, t);
  }
}
```

pero me parece bastante horrible estar llamando `strlen` y recorriendo el string por cada caracter, termina siendo O(n^2) para algo que podría ser O(n).

**Comment by ImNotGone** [comment]
pensa recorriendo alrevez

**Comment by teofum** [comment]
Ahí va, creo que encontré una mejor:

```c
int reverse(char *s, char *t) {
  if (s[0] != '\0') {
    int tail_len = reverse(s + 1, t);
    t[tail_len] = s[0];
    return tail_len + 1;
  }
  return 0;
}
```

**Comment by marcelogarberoglio** [comment]
> Ahí va, creo que encontré una mejor:
> 
> ```c
> int reverse(char *s, char *t) {
>   if (s[0] != '\0') {
>     int tail_len = reverse(s + 1, t);
>     t[tail_len] = s[0];
>     return tail_len + 1;
>   }
>   return 0;
> }
> ```
> 
> Tiene el side effect de que la llamada "base" retorna el largo del string, pero creo que la consigna no dice nada sobre el prototipo de la función.
> 
> Gracias!

Justo estaba escribiendo que además de "recorrer al revés" el enunciado te pide que sea sólo esa función pero no dice que tiene que ser void.

**Comment by ImNotGone** [comment]
si queres podes invertir el if para que no te quede indentado el codigo :D
