### ISSUE TITLE
Duda si es correcta mi solucion del TP5_ej5

### ISSUE THREAD

**Issue by JuaniRaggio** [PI-ITBA/2024_01#18]
Ejercicio 5
	Escribir una función potencia, que reciba en dos parámetros de entrada la base (de tipo double) y el exponente (entero), y devuelva el valor de dicha potencia (En no más de 10 líneas).
	Por ejemplo, potencia(2,-4) debe devolver 0.0625. En caso de no poder calcularse el resultado debe devolver –1.

Mi solucion es esta, entendiendo que 0^0=1, se me ocurrio tambien hacer todo en una sola funcion con dos whiles y dos ifs pero repetia mucho codigo

```c

double mult( double b, int exp){
    int countP, countN;
    double rta = 1.0;
    for(countP=0, countN=0; exp != countP && exp != countN; --countN, ++countP){
        rta *= b;
    }
    return rta;
}

double potencia( double base, int exponente ){
    double rta;
    if(base != 0 && exponente==0){
        rta = 1;
    } else if (base == 0 && exponente <= 0){
        rta = -1; //porque es lo que me pide el ej
    }else if (base != 0 && exponente < 0){
        rta = 1.0/(mult(base, exponente));
    } else {
        rta = mult(base, exponente);
    }
    return rta;
}



```

**Comment by marcelogarberoglio** [comment]
Está bien, después podés comparar con la solución otra forma de hacerlo.
Lo de  0^0=1 es un tema de debate, hay algunos que lo consideran igual a 1, otras teorías matemáticas consideran que no tiene resultado posible (como dividir por cero), si bien en nuestra solución lo consideramos un error, aceptaríamos que le asignen el valor 1

**Comment by JuaniRaggio** [comment]
ok gracias
