### ISSUE TITLE
TP_10 ej4

### ISSUE THREAD

**Issue by edutormakh1** [PI-ITBA/2024_01#193]
Hola buenas, no termino de entender porque mi solucion no pasa el assert:
![WhatsApp Image 2024-05-15 at 11 15 21_88896653](https://github.com/PI-ITBA/2024_01/assets/169916421/0c0d4a7c-2a17-4e12-9d64-085779df65b1)

**Comment by ImNotGone** [comment]
Corrijo: el problema creo q es que no estas generando nuevos nodos. Los valores de lista 2 que agregas ddben ser copias del original. Es decir lista 2 debe quedar intacta y lista 1 debe apuntar a nodos reservados. Ahora reviso el test, pero parece ser el caso.
