### ISSUE TITLE
problema con #include

### ISSUE THREAD

**Issue by sratto0** [PI-ITBA/2024_01#2]
Hola, que tal? 
Escribo para consultar sobre un problema que estoy teniendo al tratar de incluir la libreria stdio, y queria saber que puedo hacer para solucionarlo, o si fue un error en la instalacion del Visual Studio. Adjunto imágen:
![Screenshot 2024-03-03 173918](https://github.com/PI-ITBA/2024_01/assets/148168050/7343ee84-e30b-44a3-b64a-a8ebbecd34a5)

**Comment by marcelogarberoglio** [comment]
Hola, muy probablemente sea un error en la instalación, ya que el archivo stdio.h es parte de la biblioteca estándar. Seguramente tengas que revisar o reinstalar el Visual Studio.
