### ISSUE TITLE
Problema con errno

### ISSUE THREAD

**Issue by martunud** [PI-ITBA/2024_01#20]
Hola, queria consultar como puedo arreglar un problema que tengo con errno. En un ejercicio me piden que agregue una condicion de que si el usuario no pone la cantidad de digitos pedido, que imprima un mensaje de error. A mi se me ocurrio usar errno. Lo inicialice en 0 y despues use un if((errno != 0){ puts("Ingreso de datos invalido")} pero no me funciona. Es decir, pongo un dato invalido y el programa sigue ejecutandose hasta el final. Ya me fije de incluir la libreria y todo pero sigue sin funcionar.

**Comment by martunud** [comment]
No se si es que tengo que agregar algo en la entrada estandar o si se supone que tengo que usar otra cosa. Tambien pense en usar un return 1, pero se que esta mal visto usar returns en la mitad del codigo, ademas de que esa parte de la guia usa el assert y errno que es lo que vimos en la teorica.

**Comment by ImNotGone** [comment]
Que ejercicio es??

**Comment by martunud** [comment]
Es el ejercicio  3b del tp 5. 
#include <stdio.h>
#include "getnum.h"
#include <math.h>
#include <assert.h>
#include <errno.h>

int lugar (int num, int pos);

int main( void ){
	int boleto, esCapicua=1;
	int  j;
	errno = 0;
	boleto = getint("Ingrese un número de 5 dígitos:");
    if(errno != 0){
        puts("Ingreso incorrecto de datos");
    }
        
	for (j=1; j<=2; j++)
		if ( lugar(boleto, j) != lugar(boleto,5-j+1))
		{	
 			esCapicua=0;
			break;
		}
	printf("El boleto %ses capicúa",(esCapicua)? "":"no ");
	return 0;
}

int lugar( int num, int pos ){	
return (num / (int)pow(10, pos-1)) % 10;
}

**Comment by ImNotGone** [comment]
Sobre tu codigo, tendria en cuenta lo mencionado en los comentarios, desestimando eso el funcionamiento parece ser correcto.


```c
#include <stdio.h>
#include "getnum.h"
#include <math.h>
#include <assert.h>
#include <errno.h>

int lugar (int num, int pos);

int main( void ){
    int boleto, esCapicua=1;
    int j;
    errno = 0;
    boleto = getint("Ingrese un número de 5 dígitos:");
    if(errno != 0){
        puts("Ingreso incorrecto de datos");
    }

    // por las dudas siempre es conveniente agregarle las llaves a los if's / fors / while 
    // para evitar errores al agregar sentencias posteriormente
    for (j=1; j<=2; j++)
	if ( lugar(boleto, j) != lugar(boleto,5-j+1))
	{	
		esCapicua=0;
		// la catedra desestima fuertemente el uso de break, se prefiere el uso de flags para salir
		break; 
	}
    printf("El boleto %ses capicúa",(esCapicua)? "":"no ");
    return 0;
}

int lugar( int num, int pos ){
    return (num / (int)pow(10, pos-1)) % 10;
}
```

En cuanto a errno, la libreria en si, se compone de una variable global (errno) y un monton de macros, que indican [errores varios](https://www.thegeekstuff.com/2010/10/linux-error-codes/#:~:text=Linux%20operation%20system-,ERROR%20CODE%20TABLE,-Error%20number). Cada uno de estos codigos representa un error en particular y la idea es que distintas librerias, como por ejemplo la de matematica, puedan informar errores atravez de la variable global.

En particular el uso que le estas dando aca no es el correcto, debido a que para que funcione `getint` deberia prender con algun codigo de error errno.

**Comment by ImNotGone** [comment]
Sobre tu codigo, tendria en cuenta lo mencionado en los comentarios, desestimando eso el funcionamiento parece ser correcto.

```c
#include <stdio.h>
#include "getnum.h"
#include <math.h>
#include <assert.h>
#include <errno.h>

int lugar (int num, int pos);

int main( void ){
    int boleto, esCapicua=1;
    int j;
    errno = 0;
    boleto = getint("Ingrese un número de 5 dígitos:");
    if(errno != 0){
        puts("Ingreso incorrecto de datos");
    }

    // por las dudas siempre es conveniente agregarle las llaves a los if's / fors / while 
    // para evitar errores al agregar sentencias posteriormente
    for (j=1; j<=2; j++)
	if ( lugar(boleto, j) != lugar(boleto,5-j+1))
	{	
		esCapicua=0;
		// la catedra desestima fuertemente el uso de break, se prefiere el uso de flags para salir
		break; 
	}
    printf("El boleto %ses capicúa",(esCapicua)? "":"no ");
    return 0;
}

int lugar( int num, int pos ){
    return (num / (int)pow(10, pos-1)) % 10;
}
```

En cuanto a errno, la libreria en si, se compone de una variable global (errno) y un monton de macros, que indican [errores varios](https://www.thegeekstuff.com/2010/10/linux-error-codes/#:~:text=Linux%20operation%20system-,ERROR%20CODE%20TABLE,-Error%20number). Cada uno de estos codigos representa un error en particular y la idea es que distintas librerias, como por ejemplo la de matematica, puedan informar errores atravez de la variable global.

En particular el uso que le estas dando aca no es el correcto, debido a que para que funcione `getint` deberia prender con algun codigo de error errno. En caso de que quisieras usar errno si o si podrias hacer lo siguiente:

```c

int obtener_boleto() {
  int boleto = getint("ingrese un numero de 5 digitos");
  if (boleto / 100000 == 0 && boleto / 10000 != 0) {
    return boleto;
  }
  errno = EINVAL;
  return 0;
}

int main( void ){
 // ...
 errno = 0;
 boleto = obtener_boleto();
 if(errno == EINVAL) {
   // perror, imprime a salida de error el mensaje ingresado e informa al usuario que tipo de error fue (fijandose en errno)
   // en este caso Argumento Invalido (EINVAL)
   perror("Ingreso invalido, el numero debe ser de 5 digitos");
   // vale hacer return temprano
   return 1;
 }
 // ...
}
```
Tambien podrias hacer que el programa no falle con un while pidiendo input hasta que el usuario lo ingrese correctamente, dejo para q lo hagas vs

**Comment by ImNotGone** [comment]
cabe aclarar que no es necesario usar errno aca, podrias haber hecho esto directamente
```c
int main( void ){
    // ...
    boleto = getint("Ingrese un número de 5 dígitos:");
    if( !(boleto / 100000 == 0 && boleto / 10000 != 0) ){
        puts("Ingreso incorrecto de datos");
    }
    //...
```

Para mas informacion sobre errno este video esta bueno:
[Manejo de errores en C](https://www.youtube.com/watch?v=IZiUT-ipnj0&ab_channel=JacobSorber)

**Comment by martunud** [comment]
Perfecto, aca lo hice para numeros capicuas que incluyen mas de 5 digitos, en la entrada estandar puse el numero 12321 y me dio que es caicua, pero cuando pongo 12345654321 me da que no es capicua.:
`int inverso(int n);
int main (){
    
    int num = getint("ingrese un numero entero:\n");
    assert(sizeof(num) <= sizeof(int));
    if(num == inverso(num)){
        puts("Es capicua\n");
    } else {
        puts("no es capicua\n");
    }
    return 0;
}

int inverso (int n){
    int inverso = 0;
    while(n > 0){
        int resto = n % 10;
        inverso = (inverso*10) + resto;
        n /= 10; 
    }
    return inverso;
}`

**Comment by martunud** [comment]
Y este es usando do-while que me funciono sin problema.
`int lugar (int num, int pos);

int main( void ){
	int boleto, esCapicua=1;
	int  j;
	do {
	    boleto = getint("Ingrese un número de 5 dígitos:");
    } while ((boleto/100000) != 0);
     
	for (j=1; j<=2; j++)
		if ( lugar(boleto, j) != lugar(boleto,5-j+1))
		{	
 			esCapicua=0;
			break;
		}
	printf("El boleto %ses capicúa",(esCapicua)? "":"no ");
	return 0;
}

int lugar( int num, int pos ){	
return (num / (int)pow(10, pos-1)) % 10;
}`

**Comment by ImNotGone** [comment]
El primero te falla con 12345654321 porque el rango de los numeros enteros con signo es el siguiente [-2.147.483.648, 2.147.483.647], por lo cual el numero ingresado se excede. El 2do codigo esta bien para numeros de 5 digitos, pero por la condicion que pusiste podrian ingresarte numeros de 5 digitos o menos.
