### ISSUE TITLE
duda con el ej16 tp04

### ISSUE THREAD

**Issue by GeronimoAsin** [PI-ITBA/2024_01#21]
Hola buenas tardes, estuve haciendo el ej16 del tp04 y cuando voy a compilar el siguiente código, me tira errores por la definición de la macro. Quisiera saber el error que estoy cometiendo en la sintaxis porque busque en internet y no consigo respuesta. 
Adjunto el código: 

#include <stdio.h>
#define DIVISOR(a,b) ({ \int result; \if((b)!=0&&((a)%(b))==0){\result=1;} \else{ \result=0;} \result; \})

int main (void){

int a=10,b=-2,c;

c=DIVISOR(a,b);

printf("%d\n",c);

}

MENSAJE DEL COMPILADOR: 
ej16.c:10:4: error: expected expression
ej16.c:3:31: note: expanded from macro 'DIVISOR'
#define DIVISOR(a,b)       ({ \int result;\if((b)!=0&&((a)%(b))==0){ \result=1;}\else{\result=0;} \result;\})
                              ^
ej16.c:10:4: error: expected expression
ej16.c:3:43: note: expanded from macro 'DIVISOR'
#define DIVISOR(a,b)       ({ \int result;\if((b)!=0&&((a)%(b))==0){ \result=1;}\else{\result=0;} \result;\})
                                          ^
ej16.c:10:4: error: expected expression
ej16.c:3:107: note: expanded from macro 'DIVISOR'
#define DIVISOR(a,b)       ({ \int result;\if((b)!=0&&((a)%(b))==0){ \result=1;}\else{\result=0;} \result;\})
                                                                                                          ^
ej16.c:10:2: error: assigning to 'int' from incompatible type 'void'
c= DIVISOR(a,b);

**Comment by ImNotGone** [comment]
las \ en las macros, son para escribir macros multilineas, y se utilizan al fondo de la macro para escapar el 'newline'. El uso que le estas dando no lo termino de entender. Ejemplo:
```c
#define MACRO(x) { \
if (x == 0) { \
   return 0; \  
} \
}
```
El error que te esta dando el compilador es por que no puede expandir correctamente la macro, en este caso de todas formas lo logico seria utilizar operadores terenarios.
```c
#define DIVISOR(a,b) ( ( (b) != 0 && (a) % (b) == 0 )? 1: 0)
```
Podrias obviar el 1, 0 tambien depende el uso
```c
#define DIVISOR(a,b) ( ( (b) != 0 && (a) % (b) == 0 ) )
```

**Comment by GeronimoAsin** [comment]
si gracias, lo hice con un operador ternario pero quería probar como quedaría usando un if en una macro.
