### ISSUE TITLE
TP11_ej11

### ISSUE THREAD

**Issue by guerrerojuli** [PI-ITBA/2024_01#229]
Hola, tengo una cosulta sobre como sería la correcta resolución de este ejercicio.
Yo lo resolví de la siguiente manera: 
```c
#include "tp11_11.h"
#include <stdlib.h>

struct vectorCDT {
  elemType **vec;
  size_t cantElem;
  size_t allocSize;
  int (*cmp)(elemType source, elemType target);
};

vectorADT newVector(int (*compare)(elemType source, elemType target)) {
  vectorADT newVec = malloc(sizeof(*newVec));
  newVec->vec = NULL;
  newVec->cantElem = newVec->allocSize = 0;
  newVec->cmp = compare;
  return newVec;
}

void freeVector(vectorADT v) {
  for (int i = 0; i < v->allocSize; i++)
    if (v->vec[i] != NULL)
      free(v->vec[i]);
  free(v->vec);
  free(v);
}

size_t put(vectorADT v, elemType *elems, size_t dim, size_t index) {
  size_t oldSize = v->allocSize;
  if (v->allocSize < index + dim) {
    v->allocSize = index + dim;
    v->vec = realloc(v->vec, v->allocSize * sizeof(*v->vec));
  }
  size_t start = (oldSize < index) ? oldSize : index; // para arrancar apartir de donde necesito
  size_t indexFromStart = index - start;
  size_t countCopied = 0;
  for (int i = start, j = 0; i < index + dim; i++, j++) {
    // significa que no arrancó la parte de copiar pero estoy en una parte nueva
    if (i >= oldSize && j < indexFromStart)
      v->vec[i] = NULL;
    else if (i >= oldSize || v->vec[i] == NULL){
        v->vec[i] = malloc(sizeof(elemType));
        *v->vec[i] = elems[countCopied++];
    }
  }
  v->cantElem += countCopied;
  return countCopied;
}

int getIdx(vectorADT v, elemType elem) {
  for(int i = 0; i < v->allocSize; i++) 
    if(v->vec[i] != NULL && v->cmp(*v->vec[i], elem) == 0)
      return i;
  return -1;
}

void deleteElement(vectorADT v, size_t index) {
  if (index >= v->allocSize || v->vec[index] == NULL)
    return;
  free(v->vec[index]);
  v->vec[index] = NULL;
  v->cantElem--;
}

int elementCount(vectorADT v) {
  return v->cantElem;
}
``` 
Pero debatiendo con mis compañeros, noté que diferimos en la forma de agregar elementos al vector. Si bien también lo realizaban guardando direcciones de memoria en el mismo, lo hacían de una forma distinta. 
```c
size_t 
put(vectorADT v, elemType * elems, size_t dim, size_t index){
    if (elems==NULL){
        return 0;
    }

    if (v->size < index+dim){
        v->size=index+dim;
        v->vec=realloc(v->vec,v->size * sizeof(v->vec[0]));
    }

    int i=0;
    while (i<index){
        if (i >= v->dim){
            v->vec[i]=NULL;
        }
        i++;
    }

    size_t j=0;
    size_t elemAgreg=0;
    for (; i<index+dim ; i++){
        if (v->vec[i] == NULL || i >= v->dim){
            v->vec[i]=elems + j;  // ASIGNACIÓN
            elemAgreg++;
        }
        j++;
    }
   
    v->dim=v->size;
    v->elements+=elemAgreg;

    return elemAgreg;
}
```
En este caso, la asignación está hecha directamente guardando la posición donde se encuentra el vector original. Ellos me argumentaron muy correctamente que esto tiene un menor coste de eficiencia que realizar un malloc, que es lo que presenta mi solución, pero las razones por las que elegí realizar un malloc fueron que al asignar la dirección de memoria del vector original se reflejaran los cambios en el vector original en el vector creado, lo cual no sé si es el comportamiento buscado, y que también, si este vector es creado de forma dinámica, se podría liberar en cualquier momento y estos cambios no se verían reflejados en el vector creado por lo que sería muy facíl introducir bugs en el programa.
Quería saber cual sería la forma correcta de realizar el ejercicio y porqué, y si, sin considerar esto, mi ejercicio se encuentra resuelto de forma correcta (pasa el programa de prueba), muchas gracias.

**Comment by marcelogarberoglio** [comment]
La segunda versión no está bien, porque no guarda el elemento sino que hace referencia a un vector externo. Si después el front pisa los datos de ese vector, está cambiando los datos que supuestamente se guardaron en el TAD

Cuando se hace el realloc hay que indicar que las nuevas posiciones están libres, en tu caso setenado los nuevos elementos de vec en NULL.

**Comment by guerrerojuli** [comment]
Buenisimo, el resto del ejercicio parece estar bien realizado?
