### ISSUE TITLE
Ej3 del TP6

### ISSUE THREAD

**Issue by WaluiguiVevo** [PI-ITBA/2024_01#23]
Hola
En este ejercicio se recomienda usar const pero no estaria entendiendo como meterlo.
logre hacer este codigo que funciona correctamente con los test:
#include <stdio.h>
#include <math.h>

int distacia(double arreglo[], int size)
{
    double aux=0,dif,masdif=0;
    for (int i = 0; (i < size)||(arreglo[i]==0); i++)
    {
        dif=sqrt((pow(aux-arreglo[i],2)));
        aux=arreglo[i];
        masdif=((dif>masdif)?dif:masdif);
    }
    return masdif;
}
Me vendria bien una mano.Desde ya muchas gracias

**Comment by marcelogarberoglio** [comment]
Hola,
   vamos por partes. El uso de const sería para indicar que la función recibe un vector (la dirección del primero elemento) pero no lo va a modificar, o sea

int distacia(const double arreglo[])

y en cuanto al código, para obtener la diferencia sería más simple usar fabs, o sea
  dif=fabs(aux-arreglo[i]);

Y la condición del ciclo está mal, ya que el enunciado dice que al final del vector hay un cero, como una marca de fin, entonces sería

       for (int i = 0; arreglo[i]!=0; i++)
recorriendo el vector hasta encontrar la marca de final, y la función no recibe size. Pero como son double, puede ser cero o algo muy cercano a cero, por lo que quedaría así

       for (int i = 0; fabs(arreglo[i]) > EPSILON; i++)
siendo EPSILON una constante cercana al cero, por ejemplo 0.000001

Por otro lado, en vez de usar el condicional para asignarle a masdif un nuevo valor o el mismo valor que tenía, quedaría más prolijo usar un if: si la diferencia calculada es mayor, actualizo masdif, sinó no la modifico

Tanto para este como para el resto de los ejercicios, fijate cómo está hecho el test, que además de servir de prueba te dice cómo debe ser el prototipo de la función y cómo debería funcionar la misma.

**Comment by WaluiguiVevo** [comment]
Genial, Muchas gracias
