### ISSUE TITLE
Taller 10. ej 3 - sortedList

### ISSUE THREAD

**Issue by joseravera** [PI-ITBA/2024_01#232]
Hola, quería consultar que esá mal en este ejrcicio, porque no pasa el segundo y el tercer assert del test y no me pude dar cuenta cuál es el problema. 
Gracias!!

```C

TList sortedList (TList l) {
    if (l==NULL || l->tail == NULL) {
        return l;
    }
    TList aux = sortedList(l->tail);
    if (l->elem > aux->elem) {
        free(l);
        return aux;
    }
    l->tail = aux;
    return l;
}

```

**Comment by marcelogarberoglio** [comment]
No tiene que aceptar repetidos, es tan simple como cambiar
 if (l->elem > aux->elem) {
por
 if (l->elem >= aux->elem) {

**Comment by joseravera** [comment]
Ahí está, gracias Marcelo!!
