### ISSUE TITLE
TP05 - Ej. 10 - Duda sobre resolución

### ISSUE THREAD

**Issue by facundokrens65049** [PI-ITBA/2024_01#26]
¡Hola! Buenos días. Quería saber si mi resolución del ejercicio 5.10 es correcta. Decidí separar el código en distintas funciones pero aún así noto que se mezcla mucho el front-end con el back-end. También quería saber si es correcto utilizar 'char *' como tipo de dato para los parámetros de las funciones, para pasarles un string. 

`#include <stdio.h>
#include <math.h>
#include "../getnum.h"

int inNum(char * aclaracion);
int inDen(char * aclaracion);
void simp();
void sumFrac();

int inNum(char * aclaracion){
    int numerador = getint("Ingrese el numerador%s: ", aclaracion);
    return numerador;
}

int inDen(char * aclaracion){
    int denom;
    do{
        denom = getint("Ingrese el denominador%s, distinto de cero: ", aclaracion);
    } while (denom==0);
    return denom;
}

void menu (){
    puts("Menú de opciones:");
    puts("1 - Simplificar una fracción");
    puts("2 - Sumar dos fracciones");
    puts("3 - Terminar la ejecución");
    int opcion = getint("Por favor, ingrese un número según lo que quiera realizar: ");
    switch (opcion){
        case 1: { simp(); break; }
        case 2: { sumFrac(); break; }
        case 3: break;
        default: puts("El caracter ingresado no refiere a ninguna de las opciones.");
    }
}

void simp(){
    int num, denom, max_div=1;
    puts("SIMPLIFICAR UNA FRACCIÓN");
    num = inNum("");
    denom = inDen("");
    if (num==0) printf("La fracción resultante es: 0");
    else if (num%denom==0) printf("La fracción simplificada es igual a: %d\n", (num/denom));
    else{
        for (int i=1 ; i<=num && i<=denom ; i++) if ((num%i==0) && (denom%i==0) ) max_div = i;
        printf("La fracción simplificada es igual a : %d / %d\n", (num/max_div), (denom/max_div));
    }
}

void sumFrac(){
    int num1, denom1, num2, denom2;
    num1 = inNum(" del primer sumando");
    denom1 = inDen(" del primer sumando");
    num2 = inNum(" del segundo sumando");
    denom2 = inDen(" del segundo sumando");
    if (num1==0){
        if (num2==0) printf("El resultado es: %d\n", 0);
        else printf("El resultado es %d / %d\n", num2, denom2);
    }
    else if (num2==0) printf("El resultado es: %d / %d\n", num1, denom1);
    else if (denom1==denom2) printf("El resultado es: %d / %d\n", (num1+num2), denom1);
    else printf("El resultado es %d / %d\n", (num1*denom2 + num2*denom1), (denom1*denom2));
}

int main(void){
    menu();
    return 0;
}
`

**Comment by marcelogarberoglio** [comment]
Me parece que te complicaste un poco considerando demasiados casos especiales. Lo más simple sería:
-Crear una función que calcule el MCD
-Usarla en en la función que simplifique, que debería recibir numerador y denominador, no leerlos, e imprimir la fracción simplificada.
-La función que suma fracciones también debería recibir las dos fracciones (no leerlas), hacer la suma y llamar a simplificar fracción
