### ISSUE TITLE
Consulta libreria rand

### ISSUE THREAD

**Issue by matsdah** [PI-ITBA/2024_01#29]
Buenas tardes, como les va? Quería consultarles dónde se puede conseguir la libreria rand.h, para utilizar funciones como randInt o randomize, y si estas mismas se pueden usar en el parcial. Muchas gracias!

**Comment by ImNotGone** [comment]
la deberian haber hecho en clase, normalmente la hacen con Marcelo, si no fue asi te paso la mia.

**Comment by matsdah** [comment]
Puede ser que la hayan hecho alguna clase que me perdí, te agradecería un montón si me pasas la tuya. Muchas gracias 👍

**Comment by ImNotGone** [comment]
randlib.h
```h

#ifndef __randlib_h
#define __randlib_h

void randomize();
double randNormalize();
int randInt(int a, int b);
double randReal(double a, double b);

#endif
```
randlib.c
```c
#include <stdlib.h>
#include <time.h>

static int flag = 0;
#define RAN_RANDOMIZE {if(!flag){randomize();}}

void randomize() {
    flag = 1;
    srand((int)time(NULL));
}

double randNormalize() {
    RAN_RANDOMIZE
    return (rand()/((double) RAND_MAX + 1));
}

int randInt(int a, int b) {
    return (int)(randNormalize() * (b-a+1) + a);
}

double randReal(double a, double b){
    return (randNormalize() * (b-a) + a);
}
```

**Comment by marcelogarberoglio** [comment]
Las funciones están en la presentación 09, randInt debería ser

return (int)(randNormalize() * (b - a + 1)) + a;

parecida, pero no igual
