### ISSUE TITLE
Consulta 

### ISSUE THREAD

**Issue by pedrogonzaleznunez** [PI-ITBA/2024_01#329]
Hola, buenas tardes. Esta bien la idea de en cualquier tipo de ejercicios despreciar el primer lugar de un vector? (La posicion cero)
En strings no, simplemente en vectores para facilitar la lectura del codigo.

Hay penalización por eso?

Gracias.

**Comment by pedrogonzaleznunez** [comment]
Adjunto un ejemplo:
```c
phrasesADT newPhrasesADT(size_t keyFrom, size_t keyTo){
    if ( keyTo < keyFrom) {
        return NULL;
    }
    phrasesADT new = malloc(sizeof(phrasesCDT));
    new->size = 0;
    new->phrases =  calloc(1, (keyTo-keyFrom+2) * sizeof(phrase));
    new->keyLow = keyFrom;
    new->keyHigh = keyTo;
    return new;
}
```

Cuando reservo espacio con `keyTo-keyFrom+2`. 

Si keyFrom=1001, keyTo=1500 habrá un máximo de 500 frases a almacenar

Me reservo 501 espacios para mi ADT

**Comment by marcelogarberoglio** [comment]
Si mal no recuerdo, en algunas soluciones hemos hecho eso, por ejemplo en el Sudoku, para no estar todo el tiempo restando 1.

Pero en este caso no veo la ventaja de tener una posición de más. Sin la posición, de más, por cada clave que te pasan, le restás keyFrom para obtener la primera posición, ¿cuál es la ventaja de tener esa posición de más?
