### ISSUE TITLE
Problema VS code

### ISSUE THREAD

**Issue by Ftrivelloni** [PI-ITBA/2024_01#345]
Hola buenos dias,
Tengo un problema de no poder abrir mi carpeta con los codigos en VS code. Intente hacer lo que me pide el problema y busque en internet posibles soluciones, pero no hay caso. Quiera saber si tienen alguna idea de porque me esta ocurriendo esto ahora. 

Adjunto imagen del error en el archivo, con la "solucion" que pide el cartel ya implementada. (ya reinicie el vs code y la computadora). 
<img width="1128" alt="image" src="https://github.com/PI-ITBA/2024_01/assets/166187838/148834c9-725d-40d6-927b-96433671d3dc">

tambien paso informacion sobre informacion sobre version o demas del programa:

Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by ImNotGone** [comment]
Metete a la carpeta desde wsl y hace ` code .` ahi

**Comment by Ftrivelloni** [comment]
Listo muchas gracias!
