### ISSUE TITLE
elimina (ej 1) - 28/04/2023

### ISSUE THREAD

**Issue by jglaubart** [PI-ITBA/2024_01#346]
Buenas, queria saber si esta bien el codigo para este ejercicio. Me corre y pasa los asserts, pero no se si es la forma mas eficiente de hacerlo

```c
/*Escribir la función elimina que recibe tres strings s1, s2 y s3 y elimina de s1
aquellos caracteres que están presentes en s2 o en s3 en la misma posición que en
s1.*/

int auxCompara(char * word, int * newDim, int * i, char * s){
    while(word[*i] && s[*i]){
        if(word[*i] != s[*i]){
            word[(*newDim)++] = word[*i];
        }
        (*i)++;
    }
    return s[*i] == 0;  //si el que termino fue el string, hay que seguir
}
void elimina(char * word, char * s1, char * s2){
    int flag=0, newDim=0, i;
    for(i=0; !flag; i++){
        if (!word[i]) {
            word[newDim] = 0;
            return;
        }
        if(!s1[i]){flag=1;}
        if(!s2[i]){flag=2;}
        if(word[i] != s1[i] && word[i] != s2[i]){
            word[newDim++] = word[i];
        }
    }

    int sigue;
    if(flag==1){
        sigue = auxCompara(word, &newDim, &i, s2);
    } else sigue = auxCompara(word, &newDim, &i, s1);

    if(sigue){  //termino de copiar lo que queda del vector
        while(word[i]){
            word[newDim++] = word[i++];
        }
    }

    word[newDim] = 0;
}
```

**Comment by marcelogarberoglio** [comment]
¿Lo corriste con el flag de sanitizer? Porque acá estás preguntando por posiciones fuera de s1 o s2
 if(word[i] != s1[i] && word[i] != s2[i]){

**Comment by jglaubart** [comment]
porque estarian fuera? la flag en esa parte cambia apenas llega uno de los strings al NULL y sale del ciclo, por eso la cambio a 1 o 2 para ver cual de los dos fue el que se termino y seguir con el otro. El ultimo que deberia revisar seria el char NULL del mas corto en ese ciclo

**Comment by marcelogarberoglio** [comment]
Ah, estás usando el mismo flag. OK, no estás preguntando por fuera de los vectores, igual se podría hacer más simple, todo dentro del mismo ciclo, con un flag para determinar si ya terminó s1 y otro flag para ver si terminó s2, entonces comparás word[i] con los otros si es que el flag de cada uno no está en 1.

**Comment by jglaubart** [comment]
perfecto, ahora lo intento de esa forma. El error del sanitizer porque estaria siendo entonces?
