### ISSUE TITLE
escalable (ej. 3 - 13/04/2018)

### ISSUE THREAD

**Issue by matsdah** [PI-ITBA/2024_01#349]
Buenas tardes, espero que anden bien. Les comparto un ejercicio que encontre en un parcial: 

Se dice que una matriz de números enteros es ```escalable``` si para cada fila (excepto la primera) la suma de sus
elementos es igual a 1 + la suma de los elementos de la fila anterior, y para cada columna (excepto la primera)
se cumple que la suma de sus elementos es igual a la suma de la columna anterior +1.
Escribir una función que reciba una matriz de enteros y retorne 1 si es escalable y 0 sinó. Agregar los
parámetros que sean necesarios.

Les queria consultar si esta resolucion es aceptable, sobre todo por la repeticion de codigo en las funciones ```getSumFil``` y ```getSumCol```. Desde ya muchisimas gracias.

```c

#define COLS 10
#define FILS 10
#include <stdbool.h>

int getSumFil(char v[]);
int getSumCol(char m[][COLS], int col);

/* Devuelve si la matriz es escalable o no. */
int escalable(char m[][COLS]){
    int firstSumFil = getSumFil(m[0]);
    int firstSumCol = getSumCol(m, 0);

    for(int i = 1; i < FILS; i++){
        if (getSumFil(m[i]) != (firstSumFil + i)){
                return false;
            }
        }
    for(int j = 1; j < COLS; j++) {
        if (getSumCol(m, j) != (firstSumCol + j)){
            return false;
        }
    }
    return true;
}

int getSumFil(char v[]){
    int sum = 0;
    for(int i = 0; i < COLS; i++){
        sum += v[i];
    }
    return sum;
}

int getSumCol(char m[][COLS], int col){
    int sum = 0;
    for(int i = 0; i < FILS; i++){
        sum += m[i][col];
    }
    return sum;
}

```

**Comment by ImNotGone** [comment]
Esta bien.
