### ISSUE TITLE
Ej 3 Rec1 2020 1C 

### ISSUE THREAD

**Issue by AugustoOspal** [PI-ITBA/2024_01#356]
Buenas noches. Yo hice algo parecido a la solución publicada pero no entiendo por que esta bien una cosa. Para el caso en el que tiene que devolver 1 funciona todo bien, lo que no entiendo es: si para el caso que tiene que devolver 2, al pasarle la columna de m1 con la fila de m2, no debería fallar si en la fila de m2 están todos los números de la columna de m1 + un número que no está en la columna? Cambie una de las matrices del ejemplo de prueba para demostrarlo y falla. Por lo que pude ver en la solución oficial hace algo muy parecido a lo mío, y no entiendo cómo soluciona este problema que tengo.

```c
#include <stdio.h>
#include <stdlib.h>

#define DIM 4
#define DIRS 2

int foo(const int v[DIM], const int m[DIM][DIM], size_t fil);
int principal(const int m1[DIM][DIM], const int m2[DIM][DIM]);

int main(void)
{
	int m1[DIM][DIM] = {{1, 3, 1, 2}, {5, 5, 6, 6}, {2, 3, 4, 5}, {1, 1, 1, 2}};
	int m2[DIM][DIM] = {{1, 6, 5, 2}, {2, 6, 3, 2}, {3, 6, 2, 1}, {3, 5, 4, 1}};
	int m3[DIM][DIM] = {{1, 2, 5, 2}, {1, 3, 7, 5}, {1, 4, 4, 6}, {2, 5, 6, 6}};
	

	printf("%d\n", principal(m1, m2));
	printf("%d\n", principal(m1, m3));
}

int foo(const int v[DIM], const int m[DIM][DIM], size_t fil)
{
	size_t counter = 0;

	for (int i = 0; i < DIM; i++)
	{
		if (counter != i)
			return 0;

		for (int j = 0; j < DIM; j++)
		{
			if (v[i] == m[j][fil])
			{
				counter++;
				break;
			}
		}

	}

	if (counter == DIM)
		return 1;

	return 0;
}

int principal(const int m1[DIM][DIM], const int m2[DIM][DIM])
{
	size_t counter1 = 0, counter2 = 0;
	for (int i = 0; i < DIM; i++)
	{
		if (counter1 != i && counter2 != i)
			break;

		counter1 += foo(m1[i], m2, i);
		
		if (counter1 == DIM)
			return 1;

		counter2 += foo(m2[i], m1, i);

		if (counter2 == DIM)
			return 2;
	}

	return 0;
}
```

Saludos y gracias.

**Comment by ImNotGone** [comment]
![image](https://github.com/PI-ITBA/2024_01/assets/70904263/996e0348-683f-4b33-a2fd-2ec5a7665045)
sera otro el ej?
