### ISSUE TITLE
Rec 2020 ej 1

### ISSUE THREAD

**Issue by JuaniRaggio** [PI-ITBA/2024_01#358]
Propuse una solucion para el siguiente ejercicio pero no se si esta bien:
Se tiene una cadena que contiene números decimales separados por coma. Se requiere implementar la función void normalizar que reciba como único parámetro un string y lo normalice dejando todos los números con los decimales truncados a 2.
Se asegura que el string está bien formado:
- Sólo contiene números decimales separados por comas
- Los números no tienen signo
- Todos los números tienen al menos un dígito en la parte entera y un dígito en la parte decimal, separados por un punto.

Ejemplos 
si el string original es "12.33333,23.44444,1.0054,5.003,7.0" 
queda "12.33,23.44,1.00,5.00,7.0"
si el string original es "12.33,3.4,1.00,5.0,7.1"  queda igual
```c

#include <ctype.h>

void tillComa(char * s, int actual){
    int i = actual, copiados = 0, coma = 0;
    while(s[actual] != '\0'){
        if(s[actual] == ','){
            coma = 1;
        }
        if(coma || copiados < 2){
            s[i++] = s[actual++];
            copiados++;
        } else if(copiados >= 2){
            ++actual;
        }
    }
    s[i] = '\0';
}

void normalizar(char * s){
    int i = 0, j = 0, punto = 0;
    while(s[i] != '\0'){
        if(punto){
            tillComa(s, i);
            ++i;
        } else if(isdigit(s[i]) || s[i] == ','){
            s[j++] = s[i];
        } else if(s[i] == '.'){
            s[j++] = s[i];
            punto = 1;
        }
        ++i;
    }
s[j] = '\0'
}


```

**Comment by ImNotGone** [comment]
no deberia funcionar, porque no mantenes correctamente j.
