### ISSUE TITLE
TP_6 EJ 7

### ISSUE THREAD

**Issue by sratto0** [PI-ITBA/2024_01#37]
Buenas noches, el codigo me aborta en uno de los assert y queria saber si habia algo que me falto poner

![Screenshot 2024-04-04 220607](https://github.com/PI-ITBA/2024_01/assets/148168050/5001b3a9-f7a8-49e7-8d58-03b457d806f7)

**Comment by marcelogarberoglio** [comment]
Si ar1 se termina antes que ar2, hay que agregar a la unión los elementos que quedan en ar2. Lo mismo sin ar2 se termina antes que ar1.
En estos casos les puede servir agregar al test que imprima el resultado, con eso deberían encontrar qué está haciendo y compararlo con lo que debería hacer

**Comment by sratto0** [comment]
buenisimo, gracias!!!
