### ISSUE TITLE
Pregunta teorica 

### ISSUE THREAD

**Issue by martunud** [PI-ITBA/2024_01#377]
Hola, queria preguntar en que casos se puede usar strcpy. Tengo entendido que si se trata de strings muy largos como frases o en el ejercicio de la biblia los versiculos, se tiene que hacer una funcion a parte, al igual que no se puede usar el strcsecmp y strlen. Pero en el caso de los nombres, por ejemplo, se puede usar strcpy, strlen, strcsecmp, etc? alguien me dijo que si aparece que el nombre es constante (const) no puedo usar el strcpy e igualmente que en el otro caso, armar una funcion que copie el string en otro. Queria saber si era verdad o no, o si se tiene que hacer otra cosa. Gracias!

**Comment by marcelogarberoglio** [comment]
El criterio que se les exige en los parciales es el mismo que aplicamos en clase y en las soluciones. Podés ver las resoluciones del parcial y del recuperatorio, y también los ejercicios 12 y 16 del TP 11
