### ISSUE TITLE
multiSetADT - 27/11/2018

### ISSUE THREAD

**Issue by matsdah** [PI-ITBA/2024_01#384]
Buenas noches, espero que anden bien. Queria consultarles acerca del siguiente contrato:

![Captura de pantalla 2024-06-26 233641](https://github.com/PI-ITBA/2024_01/assets/72310148/9a84e6d2-97c6-42f0-a8b2-33302fdd7367)

La funcion newMultiSet no deberia recibir como parametro la funcion de comparacion? Porque los elementos son de tipo elemType, y por ejemplo, en una funcion recursiva addRec no podria comparar el elemento que se quiere insertar con los elementos de la lista, muchas gracias desde ya.

**Comment by marcelogarberoglio** [comment]
multiset es lo mismo que bag, que está en la guía. Son el mismo ejercicio pero con otro nombre.
O sea: sí, necesita la función de comparación.
