### ISSUE TITLE
Problemas en la instalación de gcc

### ISSUE THREAD

**Issue by SantiagoMarchetti** [PI-ITBA/2024_01#4]
Cuando quiero instalar el gcc me saltan los siguientes errores y no sé que hacer
![Screenshot 2024-03-08 124129](https://github.com/PI-ITBA/2024_01/assets/162726376/50e903ce-c277-4f91-890a-a1c223dd4a25)

**Comment by marcelogarberoglio** [comment]
El mensaje está diciendo que no puede conectarse al sitio web con IP  185.125.190.39
Recién probé y está activo. Las razones que se me ocurren son:
-En ese momento estaba caído el servidor y por eso no pudo conectarse
-En ese momento se te cortó internet
-Está mal la configuración de red

fijate desde ese mismo prompt de hacer 
ping  185.125.190.39
si no hay una respuesta, es probable que esté mal configurado y no tengas acceso a internet
si te funciona, volvé a probar

![image](https://github.com/PI-ITBA/2024_01/assets/13138167/f4c673a9-3b11-43e6-b0b1-ff922fdfd8e0)

**Comment by ImNotGone** [comment]
El otro dia a un amigo no le andaba la instalacion de maven porque tenia un proxy activado o algo asi en la mac x automatico. Te acordas que era @fmeola? Quizas es eso.

**Comment by fmeola** [comment]
> El otro dia a un amigo no le andaba la instalacion de maven porque tenia un proxy activado o algo asi en la mac x automatico. Te acordas que era @fmeola? Quizas es eso.

Cierto. Si estás usando iCloud Private Relay desactivalo. Si estás usando alguna VPN o similar también probá desactivarlo.

**Comment by marcelogarberoglio** [comment]
Claro, tendría que haber previsto que era una mac, que hacen todo pensando un informático a lo sumo hace diseño gráfico.

**Comment by ImNotGone** [comment]
No se si es una mac, pero quizas tiene un proxy.

**Comment by marcelogarberoglio** [comment]
si ese proxy filtra conexiones "no seguras" entonces sí, puede ser eso, ya que está usando HTTP y no HTTPs, la solución será desactivar el proxy, y en todo caso volver a setearlo luego de instalar
