### ISSUE TITLE
Tp6_Ej9

### ISSUE THREAD

**Issue by WaluiguiVevo** [PI-ITBA/2024_01#41]
Hola,estoy trabado con este codigo que solo me devuelve basura.
#include <stdio.h>
int desviación (const int v1[], int dim1, int v2[]);

int main(void)
{
    unsigned char arreglo[] = {0x37, 0xF2, 0x03, 0x4A, 0xFF};
    int dim = (sizeof(arreglo) / sizeof(arreglo[1]));
    int dimdesviación = dim * 2;
    int v[dimdesviación];
    desviación(arreglo, dim, v);
    for (int i = 0; i < dimdesviación; i++)
    {
        printf("%d",v[i]);
    }
    putchar("\n");
    return 0;
}

int desviación(const int v1[], int dim1, int v2[])
{
    int j=0;
    for (int i = 0; i < dim1; i++)
    {
        v2[j]=v1[i]/16;
        j++;
        v2[j]=v1[i]%16;
        j++;
    }
}

Me podrian ayudar a encotrar el error porfavor?
Desde ya muchas gracias.

**Comment by mrojaspell** [comment]
Hola, recorda que al subir un codigo encerrarlo en comillas francesas (``` código ```) así es más legible. El problema que tenés es por tener mal definidas las declaraciones de las funciones. Primero comenzás utilizando un arreglo de unsignes char pero después lo estás recibiendo en la funcion "desviación" como int. Si cambiás a:

```c
#include <stdio.h>
void desviación (const unsigned char v1[], int dim1, int v2[]);

int main(void)
{
unsigned char arreglo[] = {0x37, 0xF2, 0x03, 0x4A, 0xFF};
int dim = (sizeof(arreglo) / sizeof(arreglo[1]));
int dimdesviación = dim * 2;
int v[dimdesviación];
desviación(arreglo, dim, v);
for (int i = 0; i < dimdesviación; i++)
{
printf("%d",v[i]);
}
putchar("\n");
return 0;
}

void desviación(const unsigned char v1[], int dim1, int v2[])
{
int j=0;
for (int i = 0; i < dim1; i++)
{
v2[j]=v1[i]/16;
j++;
v2[j]=v1[i]%16;
j++;
}
}
```
debería funcionar correctamente. El problema que ocurre es que al pasarse de unsigned char a int se interpreta de manera distinta el valor por lo que termina devolviendo basura.
Un agregado, en este caso como la función desviación no retorna nada, en vez de declararla como int, podrías declararla como void y así obtener un mejor estilo de código.
