### ISSUE TITLE
TP_06 EJ 11

### ISSUE THREAD

**Issue by JuanIgnacioBridoux** [PI-ITBA/2024_01#42]
Buenos días, quería consultar si mi solución es correcta.
![Consulta PI](https://github.com/PI-ITBA/2024_01/assets/142061801/367c6f72-ccd2-4a9a-809c-7c18d63571ff)

**Comment by marcelogarberoglio** [comment]
Está bien. El for de contador podría ser con la condición  contador < filas-1, ya que cuando te queda una sola final ya está ordenado
