### ISSUE TITLE
Duda funcion rand

### ISSUE THREAD

**Issue by JuaniRaggio** [PI-ITBA/2024_01#43]
Hola, como va? Me surgio una duda en el taller de ayer y no me termino de quedar clara. Hice dos funciones auxiliares que devolvian un numero random entre 1 y 256, y la otra devolvia una letra mayuscula random.
La profe me dijo que le tenia que sumar uno a RAND_MAX pero no entiendo porque ya que si le sumo uno, nunca me devolveria el valor de la Z pero me dijo que si no le sumo uno no seria equiprobable el intervalo.

```c
#define LGAP ('Z' - 'A')
#define NGAP (256-1)

char letraRandom(){
    return (rand()/((double)RAND_MAX)*LGAP+'A');
}

int numeroRandom(){
    return ((rand()/((double)RAND_MAX))*NGAP)+1;
}

```

**Comment by mrojaspell** [comment]
Hola, no se bien cual fue la explicación de Ana (supongo que fue la profesora), pero en teoría, como rand() devuelve un numero entre 0 y RAND_MAX, sin sumarle 1 nunca podrías llegar al limite superior del intervalo en el que estás. Por lo que, para las letras te quedaría [A, Z) y para los números [1, 256). No estoy seguro si esto era lo que te dijeron, viendo tu código me inclino más a pensar que el +1 en realidad debería estar en LGAP y no en el RAND_MAX, a lo que se traduce a:
```c
#define LGAP ('Z' - 'A' +1)
```
Esto es necesario hacerlo ya que 'Z' - 'A' = 25 y la cantidad de letras en el alfabeto inglés son 26 por lo que te estarías quedando corto por 1 letra (de ahí el +1). 

Si no quedó claro o no contesté tu pregunta repreguntá sin problema.

**Comment by marcelogarberoglio** [comment]
Además de lo que comenta Máximo, está el tema de por qué sumarle 1 a RAND_MAX para dividir
Eso se explicó en la clase teórica, cuando se contruyó la bilbioteca para números aleaotorios. 
La función rand() devuelve un número entre 0 y RAND_MAX **inclusive**, entonces en teoría esata cuenta te podría retornar un valor entre 1 y 6



pero sólo te va a devolver 6 cuando rand retorne RAND_MAX, algo muy poco probable. Sería como tirar miles de veces un dado y que de esas miles sólo una vez salga el 6, por eso la cuenta correcta para un número entre 1 y 6 es

1 + rand() / ((double) RAND_MAX+1) * 6

**Comment by JuaniRaggio** [comment]
Si, la explicacion de ana era exactamente eso que es muy poco probable que rand() devuelva RAND_MAX pero eso es lo que no me termina de convencer, entiendo que es una cuestion de como esta construido rand()

**Comment by marcelogarberoglio** [comment]
¿No te convencen las probabilidades?, lo que dirían Pascal, Fermat y Gauss. RAND_MAX suele valer 2147483647, eso quiere decir que si hago

(int)  ( (rand() / (double) RAND_MAX) * ('Z' - 'A' +1) )

en teoría estoy obteniendo valores entre 'A' y 'Z', pero la 'Z' va a salir sólamente 1 de cada 2147483647 veces, cuando rand() retorne RAND_MAX. La estamos tirando al muere a la pobre Z.

Pero bueno, si no estás del todo convencido, usá esa cuenta, guardá en un vector de 26 elementos las veces que aparece cada letra en un ciclo de 10 millones de veces y después fijate cuántes veces aparece la 'Z' en relación con las otras.
