### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by pedrogonzaleznunez** [PI-ITBA/2024_01#432]
Buenas tardes, hay algún ejemplo que pueda ver un iterador para un ADT con vectores?

Recuerdo haber visto en clase iteradores de listas, pero no recuerdo de vectores.

**Comment by marcelogarberoglio** [comment]
Se hizo en clase, no sé si quedó grabado. Si aprobaron la cursada no deberían tener problema en trasladar el concepto de iterar una lista a iterar en un vector.
