### ISSUE TITLE
fsanitize : memory leaks

### ISSUE THREAD

**Issue by facundokrens65049** [PI-ITBA/2024_01#442]
Buenas! Probamos el código y funciona, pero al compilar con -fsanitize=address, en algunas computadoras, muestra un monton de mensajes indicando "indirect memory leaks", al finalizar la ejecución. Se trata de un error, de un warning o simplemente hay que ignorarlo?

Último mensaje del fsanitize: 
SUMMARY: AddressSanitizer: 31051 byte(s) leaked in 1906 allocation(s).

**Comment by facundokrens65049** [comment]
Creo que hay una consulta similar: #440

**Comment by marcelogarberoglio** [comment]
Misma respuesta que en #440
