### ISSUE TITLE
Consulta comentatios tp final

### ISSUE THREAD

**Issue by juan43963** [PI-ITBA/2024_01#449]
buenas, pregunta media tonta, Deberíamos escribir los comentarios en inglés si nuestras variables están en inglés?

**Comment by marcelogarberoglio** [comment]
No necesariamente. Lo que no queda bien es que algunos comentarios estén en castellano y otros en inglés. Lo mismo con los identificadores, deberían tener un criterio uniforme.

**Comment by juan43963** [comment]
Perfecto!! muchas gracias!
