### ISSUE TITLE
Ejs Promedio - Parcial 2011  

### ISSUE THREAD

**Issue by juan43963** [PI-ITBA/2024_01#46]
Buenas! como andan? quisiera saber si esta bien este ejercicio 

<img width="728" alt="Captura de pantalla 2024-04-07 a la(s) 10 27 57" src="https://github.com/PI-ITBA/2024_01/assets/107368772/aed0604a-6ecf-4e9b-9f94-186b6ef749b9">
<img width="801" alt="Captura de pantalla 2024-04-07 a la(s) 10 40 09" src="https://github.com/PI-ITBA/2024_01/assets/107368772/e5c1addb-153b-48d0-82c7-f0800d720a8f">

Tengo algunas dudas sobre este ej:
1- linea 9 y 10, "limFils" y "limCols"
2-funcion copy -> me genera duda la condicion " i != fila" y " j != col" 

estan bien definidos asi?

saludos

**Comment by marcelogarberoglio** [comment]
Me parece que no están bien los incrementos de i y j en los dos for de matriz. Para la próxima, sería mejor si envían el código en vez de una foto, para poder marcarles mejor el error o devolverles el código corregido.
