### ISSUE TITLE
Ej Buscaminas - recu 2023 2C

### ISSUE THREAD

**Issue by juan43963** [PI-ITBA/2024_01#47]
Buenas! molesto de nuevo jajaj, quisiera saber si esta bien este ej
(adjunto enunciado y resolucion)
<img width="1015" alt="Captura de pantalla 2024-04-07 a la(s) 10 47 29" src="https://github.com/PI-ITBA/2024_01/assets/107368772/eb94bbfb-9b94-4e8a-8bdb-e0143d675b82">
<img width="927" alt="Captura de pantalla 2024-04-07 a la(s) 10 48 25" src="https://github.com/PI-ITBA/2024_01/assets/107368772/d252d942-24c8-4c48-9053-7baa2c50ab30">

**Comment by juan43963** [comment]
me olvide de borrar los comentarios! eran para guiarme cuando pensaba el ej!

**Comment by marcelogarberoglio** [comment]
¿Lo probaste? Estás recorriendo desde fil-3 hasta fil+3, eso no me parece que es recorrer los adyacentes. Además, seguramente por copy-paste estás recorriendo en base a fil tanto el i (las filas) como el j (las columnas)
Tal vez sería más sencillo si, para el caso en que en una celda haya un número >=0 le pidas que recorra los adyacentes y te devuelva cuántas minas hay, si coincide con el número está bien. No sé si tiene sentido complicarse cortando antes el recorrido de los adyacentes en caso de que te pases de la cantidad, ya que es nada más que una matriz de 3x3.
