### ISSUE TITLE
Macros vs funciones inline

### ISSUE THREAD

**Issue by teofum** [PI-ITBA/2024_01#5]
Estaba viendo los slides de 07 - Preprocesador, y veo que como razón principal para declarar "funciones" muy cortas como macros de preprocesador mencionan que elimina el overhead de una llamada de función. Eso me generó la duda de si no cumple el mismo rol y de un modo más idiomático declarar una función `inline`, por ejemplo:

```c
#define PI 3.141529
#define CIRCLE_AREA(r) (PI * r * r)

// vs

static inline double circle_area(double r) {
    return PI * r * r;
}
```

como en principio una función `inline` se reemplaza con su código interno en tiempo de compilación, pero mantiene las semánticas de una función al programar.

Duda secundaria: el compiler de C hace alguna optimización y automáticamente hace `inline` a funciones muy cortas, como algunos lenguajes más modernos (eg Rust)?

**Comment by marcelogarberoglio** [comment]
Sí, también podrían usar funciones inline. Es una de las características propias de C que no mencionamos en la materia. Como dijimos en clase, usamos el lenguaje C pero el objetivo principal del curso es justamente el nombre: "Programación imperativa", entonces muchas características propias de C no se mencionan, hacemos foco en el desarrollo de algoritmos, eficientes y con buen estilo.
En cuanto a la duda secundaria, la rta es sí, los compiladores hacen distintos tipos de optimizaciones, incluso gcc tiene varios parémetros para especificar si uno desea que haga menos, más o determinadas optimizaciones.

**Comment by ImNotGone** [comment]
Con las macros siempre pasa lo esperado, se remplazan en el lugar asignado y reducen el overhead por asi decirlo debido a que no hacen un llamado a funcion, el cual realiza varias acciones en al assembler resultante (tiene q saltar a la dir de memoria, reservar espacio en el stack etc).
Las funciones inline tienen un comportamiento similar, cuando el compilador decide utilizarlas, si no me acuerdo mal hay algunos casos en los cuales sin importar que le hayas puesto inline, igualmente no las remplaza como seria esperado.
Para mas informacion sobre inline, este video esta bueno:  [The Inline Keyword in C.]( https://www.youtube.com/watch?v=t6Jfrmdg5rk&ab_channel=JacobSorber).

**Comment by ImNotGone** [comment]
Minuto 8:40 se ve que el compilador ignora el inline.

**Comment by teofum** [comment]
Perfecto, gracias! No tenía del todo claro el comportamiento de `inline` en C, por lo que veo es relativamente complejo y hasta sólo con `static inline` quedan muchas cosas que dependen del compiler. Creo que entiendo un poco mejor por qué se ven tantas macros en código C incluso teniendo `inline`
