### ISSUE TITLE
tp6_ej9

### ISSUE THREAD

**Issue by Ftrivelloni** [PI-ITBA/2024_01#61]
Hola, tengo un problema cuando corro el test ya que el programa no termina de correr. No logro tampoco encontrar el bucle infinito ya que todos los for a mi enternder tienen clara condicion de corte (Haga o no haga el programa lo que tengo intencion). Tambien tengo una duda acerca de guardar vectores dentro de otros, aunque no me tire warning, me parece que no me queda bien definida dimResp. Ultima duda, en la funcion "leerNum" poner la dimension de vector char como 4 directamente se considera magic number?
```c
// Funcion que me convierte de sistema hexa a decimal
unsigned char leerCar(unsigned char num) {
     if (num >= '0' && num <= '9') {
        return num - '0';
    } else {
       switch (num)
       {
       case 'A':
        return 10;
        break;
        case 'B':
        return 11;
        case 'C':
        return 12;
        case 'D':   
        return 13;
        case 'E':
        return 14;
        case 'F':
        return 15;
       default:
        break;
       } 
    } 
    return 0;
}    

// Funcion que empieza a leer los caracteres luego de la x
unsigned char leerNum(unsigned char num) {
int encontradaX = 0, dimResp = 0;
unsigned char v[4];
for (int i = 0; i < 4; i++)
{
    num = getchar();
    if (encontradaX) {

        v[dimResp++] = leerCar(num);
    }
    
    if (num == 'x') {
        encontradaX = 1;
    }
}
return v[dimResp];
}

// Funcion desvio estandar, guarda un vector dentro de otro...
double desv(const unsigned char vector[], int dim) {
    int dimResp = 0, b[dimResp];

for (int i = 0; i < dim; i++) {
    b[dimResp++] = leerNum(vector[i]);
}
return b[dimResp];
}

```

**Comment by marcelogarberoglio** [comment]
Me parece que no entendiste la consigna, no es un vector donde estén los valores ASCII representando hexadecimales.
La función es de backend, no hay que hacer getchar sino recorrer el vector que nos pasan, donde en cada byte tengo dos valores (4 bits cada uno).
Fijate en el test cómo están inicializados los vectores y qué representa cada elemento del vector. Cualquier duda sobre el enunciado o el test volvenos a escribir.

**Comment by Ftrivelloni** [comment]
Dale perfecto muchas gracias!!

**Comment by Ftrivelloni** [comment]
Ahora que sigo la consigna y corre el test, pero aborta en el primer assert. No entiendo al 100% que intepretar del fallo de este assert en particular. Por ende no se donde buscar exactamente mi error. 
```c
unsigned char arreglo2[] = { 0x33, 0x33, 0x33, 0x33, 0x33 };
  for(int i=0; i <= 10; i++)
    assert(desv(arreglo2, i)==0);
``` 
Este es mi codigo:
```c
#include <stdio.h>
#include <assert.h>
#include <math.h>
//los 4 bits bajos
char nibblelow(char num) {
    return num & 0x0F;
}
//los 4 bits altos
char nibblehigh(char num) {
    return num>>4;
}

//promedio de la suma de los bits
double prom(const unsigned vector[], int dim) {
    double suma = 0;
    int dimAux = dim;
    for (int i = 0; dimAux > 0; i++, dimAux--)
    {
        suma += nibblehigh(vector[i]);
        suma += nibblelow(vector[i]);
    }
    return suma/dim;

}

//El  la sumatoria del bit menos su promedio al cuadrado
double sumatoria( double promedio, const unsigned char vector[], int dim){
    double suma = 0;
    for(int i = 0; dim > 0; i++, dim--) {
        suma += pow(nibblehigh(vector[i]) - promedio, 2);
        suma += pow(nibblelow(vector[i]) - promedio, 2);
    }
    return suma;
}


double  desv(const unsigned char vector[], int dim) {
    double promedio, suma;
    promedio = prom(vector, dim);
    suma =sumatoria(promedio, vector, dim);
    return sqrt(suma/dim);
}
``` 
Saludos.

**Comment by marcelogarberoglio** [comment]
¿No te tira warnings? En prom estás diciendo que el vector que recibís es de int, no de char
Dim es la cantidad de valores de 4 bits que hay almacenados, fijate en el ejemplo. Si hay 3 valores, entonces el vector
v[] = { 0x23, 0xF4 }  tiene los valores 2, 3 y 15, donde en v[0] están tanto el 2 como el 3, y en v[1] está el 15. el nibble con el valor 4 se descarta, no se usa.
En el vector puede haber cantidad par o impar de nibbles
nibblehigh debería recibir unsigned char, ya que el decalaje conserva el bit de signo

**Comment by Ftrivelloni** [comment]
Sobre el warning, no se porque no me tiraba warning pero ahi lo arregle. Entonces tanto en prom() como en sumatoria() deberia decrementar dim luego de sumar cada nibble? en vez de decrementar dim luego de sumar ambos nibbles. Entonces me quedaria asi el for() del  prom() por ejemplo. 
```c
 for (int i = 0; dimAux > 0; i++, dimAux--)
    {
        suma += nibblehigh(vector[i]);
        if (dim--)
        {
         suma += nibblelow(vector[i]);
        }
```
