### ISSUE TITLE
Duda de estilo: declaración de variables

### ISSUE THREAD

**Issue by teofum** [PI-ITBA/2024_01#7]
Medio una pavada la consulta, pero veo en los programas de ejemplo de las guías y del libro que se suelen declarar todas las variables que usa una función al comienzo y luego se asignan, por ejemplo:

```c
int main(void) {
  int foo, bar, baz, i;
  float x, y;

  foo = 5;
  bar = 20;

  // Código que hace algo...

  for (i = 0; i < bar; ++i) {
    y = foo / (float) i;
    x = bar / (float) i;
    // ...
  }
  baz = x + y;

  // ...
}
```

¿Esto es convención de C? ¿Se hace por algo? Intuitivamente, tiene más sentido declarar las variables lo más cerca posible de su uso:

```c
int main(void) {
  int foo = 5;
  int bar = 20;

  // Código que hace algo...

  float x, y;
  for (int i = 0; i < bar; ++i) {
    y = foo / (float) i;
    x = bar / (float) i;
    // ...
  }
  int baz = x + y;

  // ...
}
```

Hasta donde conocía este último estilo es lo que se recomienda en C++ y otros lenguajes (muchos dan warnings por dejar variables sin inicializar, o directamente ni compilan), y parece tener varias ventajas:
- Es más claro a partir de dónde se usa una variable en el código
- No hay variables sin inicializar dando vueltas, osea no hay posibilidad de bugs por leer basura
- Respeta mejor el scope, en el caso de la variable de iteración de un `for` por ejemplo, significa que `i` sólo existe en el loop

¿Es convención declarar todas las variables primero por algo o es simplemente cuestión de costumbre? No me queda claro el patrón. (Tal vez más importante, ¿en los TP y parciales esperan que se use el primer estilo con todas las declaraciones juntas?)

**Comment by ImNotGone** [comment]
Tengo entendido que recien a partir de c99 no fue necesario declarar las variables al principio. [Ejemplo](https://stackoverflow.com/questions/288441/variable-declaration-placement-in-c). Es mas una costumbre que otra cosa. Creo que la catedra no tiene problema con donde pones las variables, mientras no sea un caso super raro, pero que te confirme @marcelogarberoglio

**Comment by teofum** [comment]
Ouch, no conocía esa, gracias!
