### ISSUE TITLE
Solución del TP6 03

### ISSUE THREAD

**Issue by teofum** [PI-ITBA/2024_01#77]
Buenas! Estaba viendo las soluciones del TP6 y veo que en las del ejercicio 3, donde la función toma un array de `double` y espera que esté terminado con 0, hace el check con un epsilon:

```c
if ( fabs(arreglo[0]) > EPSILON ) { ... }
```

Es necesario el epsilon en este caso? Dado que el 0 es un valor arbitrario de fin, no el resultado de alguna cuenta, parecería ser el caso borde donde se puede comparar el valor exacto (y dependiendo del contexto podría venir bien, por ejemplo para distinguir un 0 terminador de una cuenta que dio cerca de 0).

**Comment by marcelogarberoglio** [comment]
Sí, podrías cambiar por 0.0, o definir EPSILON como 0.0
