### ISSUE TITLE
TP 3 Ejercicio 15

### ISSUE THREAD

**Issue by lomendez** [PI-ITBA/2024_01#8]
Hola, estoy teniendo problemas con el ejercicio 15 del TP3. La consigna dice: "Dado un entero que representa un número binario positivo (todos sus dígitos son cero o uno), imprimir por salida estándar  el equivalente decimal. (En no más de 10 líneas). Utilizá la función getint para recibir el entero, y aplicá las operaciones matemáticas necesarias para obtener el decimal. ¿Cómo validarías que el número ingresado no es binario?." La parte que no me estaría saliendo es la de validar que el número que se ingresa sea binario. Estuve intentando buscar el error hace rato pero no lo logro, les agradecería si me lo pudieran indicar. Muchas gracias, Lorenzo.

**Código**:
```
#include <stdio.h>
#include "../getnum.h"
#include <math.h>

int main(void){

    int binario = 0; /*Defino un flag que indica si el número ingresado es binario (Lo inicializo en falso)*/

    while (binario == 0){
        int num = getint("Ingrese un número binario: "), aux = num;  /*Uso una variable auxiliar para guardar el valor ingresado para después*/
        binario = 1; /*Cambio el flag a verdadero para que si no se detecta nada fuera de lo normal, quede indicado que el número es binario*/
 
        while (aux != 0 && binario==1 ){ /*Mientras el número no haya llegado a 0 y mientras no se haya detectado que el número no es binario...*/
            if ((aux%10) > 1){
                printf("El número no es binario"); /*... Valido que lo sea usando el módulo en base 10 (si es binario da 1 o 0, o sea menor o igual a 1) */
                binario = 0;
            }
            aux /=10; /*Paso al siguiente dígito*/
        }
    }
    int decimal = 0, i, num;
    for (i= 0; num != 0; i++){
            decimal += num % 2 * pow(2,i);  /*Conversión a decimal*/
            num /= 10;
        }
        printf("El número en decimal es %d\n", decimal);
        return 0;
}
```

**Terminal**:
`gcc tp3_ej15_2.c ../getnum.c -o tp3_ej15_2  -Wall -pedantic -std=c99 -lm`

Ingrese un número binario: 1010
El número en decimal es 10

Ingrese un número binario: 3
El número en decimal es 1

**Comment by marcelogarberoglio** [comment]
La lógica está bien, el problema debe estar en el operador coma, que retorna el valor de la última expresión de la derecha, probá con
  int num = getint("Ingrese un número binario: ");
 aux = num; 

También podrías ir haciendo la conversión a medida que validás los dígitos, para evitar hacer dos ciclos
Y se supone que se puede hacer sin usar pow, pensá que primero necesitás el valor de 2 elevado a la cero, luego dos elevado a la 1, luego 2 elevado a la 2, etc. donde cada valor es igual al anterior multiplicado por 2

**Comment by lomendez** [comment]
Gracias por la ayuda profesor, ya me quedó todo claro y lo pude resolver.
