### ISSUE TITLE
TP 6 Ej 17

### ISSUE THREAD

**Issue by sratto0** [PI-ITBA/2024_01#80]
Buenas noches, queria saber si el codigo que arme para el ejercicio 17(pasa el test) tiene buen estilo y es eficiente

```c
int puede(int mat[][M], int f){
    for(int i=0;i<M;i++){
        if(mat[f][i]>9 || mat[f][i]<0){
            return 0;
        }
    }
    return 1;
}

int armado(int mat[][M], int f){
    int rta=0, dim=M-1;
    for(int i=0;i<M;i++){
        rta+=(mat[f][i]*pow(10, dim--));
    }
    return rta;
}

int armaFilas(int mat[][M], int vec[]){
    int i, k=0;
    for(i=0;i<M;i++){
        if(puede(mat, i)){
            vec[k++]=armado(mat, i);
        }
    }
    return k;
}
```

**Comment by marcelogarberoglio** [comment]
Se podría hacer en un mismo proceso el armado y validación del número, o sea que armado podría retornar el número o -1 para que se descarte
También se puede evitar usar pow(10,0), luego pow(10,1), pow(10,2), etc. y en vez de eso armar el número como se hizo en las primeras prácticas, si los dígitos son 1 2 3 4, primero tenemos 0, luiego 0 * 10 + 1, luego 1* 10 + 2, luego 12 * 10 + 3, etc
