### ISSUE TITLE
Duda funcion elimina

### ISSUE THREAD

**Issue by JuaniRaggio** [PI-ITBA/2024_01#85]
Hola, hice la prueba de respondus y logre hacer el ejercicio que plantearon pero nose si esta bien, siento que si lo hacia con 2 ciclos iba a ser mucho mas facil pero mucho menos eficiente por lo que tarde mucho mas pero lo pude hacer en uno. El ejercicio decia que dados v1, dim1, v2, dim2 vectores ordenados crecientemente y dim1, dim2 sus respectivas dimensiones, borrar de v1 los elementos que esten en v2 y devolver en el nombre de la funcion la nueva dimension de v1.

```c

int elimina(int v1[], int dim1, int v2[], int dim2){
    if(dim1 == 0 || dim2 == 0){
        return dim1;
    }
    int i = 0, j = 0, sec = 1;
    while(i<dim1){
        if(v1[i] == v2[j] && j<dim2){
            v1[i] = v2[i+sec];
            ++j;
            ++sec;
        } else if(v1[i]>v2[j] && j<dim2){
            ++j;
        } else if(v1[i]<v2[j] || j>dim2){
            ++i;
            if(sec>1){
                v1[i] = v1[i + sec];
            }
        }
    }
    return (dim1-sec+1);
}



```

`

**Comment by marcelogarberoglio** [comment]
¿Pudiste probarlo?
Si j llega a dim2, me parece que no entra a ningún if dentro del while, y entonces no se cambia i

Cuando hac;és
 if(v1[i] == v2[j] && j<dim2){
            v1[i] = v2[i+sec];

hay dos errores: primero preguntás por v2[j] y luego si j es un índice válido, tendría que ser al revés
estás copiando algo de v2 en v1

Cuando se quiere eliminar elementos de un vector, la idea es hacer algo parecido a eliminaCeros
Y se puede hacer recorriendo una sola vez cada vector

**Comment by JuaniRaggio** [comment]
ahi vi, lo de v2 en v1, eran los dos v1 , nose porque puse v2. En el ultimo if deberia ir un (== j) y con eso estaria bien?
