### ISSUE TITLE
tp2 ej 8 

### ISSUE THREAD

**Issue by marr64** [PI-ITBA/2024_01#9]
Buenas tardes! queria mandar el ej 8 del tp2 y ver si hay cosas para mejorar o si esta bien. 
Probe el programita con algunos valores y funciono, pero de igual manera me gustaria un feedback.
<img width="680" alt="Screen Shot 2024-03-16 at 15 29 17" src="https://github.com/PI-ITBA/2024_01/assets/127711549/aeb7b3e5-140e-4afc-b8d5-e930e86514f4">

**Comment by marcelogarberoglio** [comment]
Está bien. Si bien podría decirse que aparecen "magic numbers", son valores conocidos y que no deberían cambiar, por lo que es aceptable usarlos sin haber credo #define para cada uno de ellos.
