### ISSUE TITLE
Algoritmo recorrer cuadrantes

### ISSUE THREAD

**Issue by Pablo-Goros** [PI-ITBA/2024_01#91]
Hola como va? Tenia una consulta sobre un algoritmo que suele aparecer en muchos ejercicios de recorrer una cuadrante de una matriz (Por ejemplo en el caso de sudoku que hay que recorrer un cuadrante de 3x3). Queria saber si es que este planteo "generico" esta bien. Ademas queria saber si es que la claridad del codigo esta bien? No estoy seguro si seria necesario definir variables auxiliares como inicio_fila y fin_fila para mejorar la claridad dentro del for.
Desde ya muchas gracias!

```c

void recorro_cuadrante(int matriz[][DIM], int pos_fila, int pos_columna, int n) {
    int lado = (n - 1) / 2; // voy a recorrer esto a cada lado de la posicion indicada

    for (int fila = pos_fila - lado; fila <= pos_fila + lado; fila++) {
        for (int columna = pos_columna - lado; columna <= pos_columna + lado; columna++) {
            
            // esto dentro del rango?
            if (0 <= fila && fila < DIM && 0 <= columna && columna < DIM) {
                // haces lo que tengas que hacer.
            }

            // caso donde no tengo que recorrer la posicion que me dan
            if ((0 <= fila && fila < DIM) && (0 <= columna && columna < DIM) && (fila != pos_fila) && (columna != pos_columna)) {
                // haces lo que tengas que hacer.
            }
        }
    }
}

```

**Comment by marcelogarberoglio** [comment]
Sí, esa es una forma de recorrer una submatriz que tiene como centro una coordenada determinada. La otra forma es como hacemos en la solución del sudoku que le pasamos la coordenada de la primer fila y columna.
Para una forma más eficiente de no acceder a las posiciones que están fuera de la matriz podés ver la solución al ejercicio 15 del TP 6.
